### PR TITLE
virtio-devices, vmm: Remove PTY resize handler

### PR DESCRIPTION
**Pull request by sboeuf**
Given the PTY resize handler isn't working and we can't properly figure
out a way to fix this issue, it's better to remove the code rather than
keeping it broken.

Users can still resize the terminal manually from the guest if the size
doesn't fit the terminal on the host.

Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

### CODE REVIEW

**Comment by alyssais** [comment]
Hi, PTY resize is important to me, and I'd prefer to describe how to test in than to see it removed.  I'm just building myself cloud-hypervisor HEAD to make sure it still works, and then I'll write up how to test it.

**Comment by sboeuf** [comment]
> Hi, PTY resize is important to me, and I'd prefer to describe how to test in than to see it removed. I'm just building myself cloud-hypervisor HEAD to make sure it still works, and then I'll write up how to test it.

Ok sounds good. In case it doesn't work with HEAD, try with the version when you introduced the support for it. It'll be very useful to have proper instructions to test it in order to move forward and fix it if needed.

**Comment by alyssais** [comment]
# How to test PTY resizing in cloud-hypervisor

## Get a terminal emulator that supports attaching to a PTY, and sending it resize events

Most terminal emulators don't support attaching to a terminal emulator at all.  Screen does, but it doesn't send it resize events.  I [sent them](https://lists.gnu.org/archive/html/screen-devel/2022-04/msg00000.html) a tiny patch to fix this, but screen maintenance seems to be a bit spotty…  I've also [implemented](https://spectrum-os.org/git/nixpkgs/plain/pkgs/applications/terminal-emulators/foot/Add-support-for-opening-an-existing-PTY.patch?h=rootfs&id=77f0d1e4e66735495ac28d60655e781bf28d4a9b) support for attaching to PTYs in the [foot](https://codeberg.org/dnkl/foot/) terminal emulator, and there resize just works — upstream seemed tentatively interested when I spoke to them, but I haven't got a chance to submit it upstream yet.

So, for now, the easiest way to test is to build screen with my small patch applied:
(Here'e the [patch](https://github.com/cloud-hypervisor/cloud-hypervisor/files/9494888/screen-pty-resize.patch.txt) for convenience as screen's mailing list archive doesn't seem to allow downloading the raw message.)

```ShellSession
dnf install -y wget patchutils autoconf automake gcc ncurses-devel # or as appropriate for your distro
wget https://ftp.gnu.org/gnu/screen/screen-4.9.0.tar.gz https://github.com/cloud-hypervisor/cloud-hypervisor/files/9494888/screen-pty-resize.patch.txt
tar xf screen-4.9.0.tar.gz
cd screen-4.9.0
patch -p1 < ../screen-pty-resize.patch.txt
./configure
make
```

Now there's a `screen` executable in the root of the source directory.

## Run cloud-hypervisor

Make sure to pass `--console pty`, and `--api-socket`.

## Find the path to the TTY

```ShellSession
ch-remote --api-socket /path/to/api-socket info | jq -r .config.console.file
```

## Attach screen to the PTY

```ShellSession
./screen /dev/pts/7 # or whatever PTY ch-remote said
```

Once attached, I recommend running a program like tmux or mg, so it's easy to see if resize is working based on the status bar it draws at the bottom.

I've tested this with 2a222b2692bf55c9a0b5c84edc624d7d3c4a8d0a, and it worked fine.

Finally, apologies for not being on top of my GitHub notifications recently.

**Comment by sboeuf** [comment]
@alyssais Ahhh I understand now, you had to modify existing tools. Thanks for checking this is still working, I'm glad to see the support didn't get broken.
I'll have a try with a patched version of screen.

**Comment by sboeuf** [comment]
I confirm with the patched version of `screen`, PTY resize works fine!

**Pull request closed without merging**
