### PR TITLE
build: Update rust-vmm dependencies

### PR DESCRIPTION
**Pull request by likebreath**
Particularly update kvm-bindings, kvm-ioctls, vfio-bindings, and vfio-ioctls.

### CODE REVIEW

**Review by liuw — APPROVED** [review]

**Comment by likebreath** [comment]
The `test_ovs_dpdk` test is constantly failing, let me take a look closer look.

**Comment by likebreath** [comment]
I confirmed that the latest release of the `kvm-bindings` crate breaks our snapshot/restore and live-migration in general.  A proposal is sent to address this issue and let's see how it goes:  https://github.com/rust-vmm/kvm-bindings/pull/113.

**Comment by ymjing** [comment]
Gentle ping. https://github.com/rust-vmm/kvm-bindings/pull/113 has been merged.

**Comment by likebreath** [comment]
> Gentle ping. [rust-vmm/kvm-bindings#113](https://github.com/rust-vmm/kvm-bindings/pull/113) has been merged.

We will need to wait for a new point release to include this fix before we can move forward with this PR. A PR is pending for this point release: https://github.com/rust-vmm/kvm-bindings/pull/115

**Comment by likebreath** [comment]
Just a heads-up what to expect. There are few other dependencies that also consumes `kvm-bindings`, such as `kvm-ioctl`, `vfio-bindings`, and `vfio-ioctl`. We will need to update these crates too or even need a new release. Meanwhile, the `vm-memory` crate just had a new release too, and I will also include its version bump in this PR.

I am on it [1] and there will be few more PRs to be sent. Hopefully we can have everything ready by early next week.

[1] https://github.com/rust-vmm/kvm-ioctls/pull/277

**Pull request merged**
