### PR TITLE
tests: Simplify 'test_memory_mergeable'

### PR DESCRIPTION
**Pull request by likebreath**
We now reply on the value from '/sys/kernel/mm/ksm/shared_pages' to
validate our "--memory mergeable=on|off" option. For `mergeable=on`,
we are expecting to see more 'shared_pages' reported by the kernel when
we start more VMs with this option. For `mergeable=off`, we are
expecting the 'shared_pages' value to be always 0, as we are assuming
the rest of the system (in our CI) is not using mergeable memory.

Fixes: #2138

Signed-off-by: Bo Chen <chen.bo@intel.com>

### CODE REVIEW

**Comment by likebreath** [comment]
@rbradford @sboeuf Please let me know whether you think the current testing logic is sufficient. It may be the simplest, which only checks the `shared_pages` number increases when we start more VMs with the `mergeable=on` option. 

Please let me know if you want the logic to be more thorough/precise. For your reference: some data reported from the current test.

```
old ksm pages_shared 7207, new ksm pages_shared 42995
old ksm pages_shared 7234, new ksm pages_shared 42061
old ksm pages_shared 7222, new ksm pages_shared 42768
```

**Review by sboeuf — COMMENTED** [review]
@likebreath this looks good to me. It's good to see this is reducing the testing time since we're not waiting for the VM's memory to stabilize before we can get the amount of memory actually consumed.

One nit, now that `test_memory_mergeable_on()` does not rely on `test_memory_mergeable()`, there's no need for a `test_memory_mergeable()` function, as it can directly be `test_memory_mergeable_off()`.

**Comment by likebreath** [comment]
@sboeuf PTAL. PR updated as our discussions today. Now both tests (`mergeable_on/off`) are running under 30 seconds on my local machine. Let's see how it works in the CI environment, e.g. whether our assumption that the system is not using any mergeable memory.

**Review by sboeuf — APPROVED** [review]

**Comment by likebreath** [comment]
Looks like booting with `hypervisor-fw` is not working on aarch64?  I changed the test to use direct kernel boot to fix the issue. Please let me know if I miss anything. Thank you.

<details><summary>The `test_memory_mergeable_off` on aarch64 got the following error.</summary>
<p>

```
==== Start cloud-hypervisor command-line ====

"target/aarch64-unknown-linux-gnu/release/cloud-hypervisor" "--cpus" "boot=1" "--memory" "size=512M,mergeable=off" 
"--kernel" "/root/workloads/Image" "--disk" "path=/tmp/chepIHzh/osdisk.img" "path=/tmp/chepIHzh/cloudinit" 
"--net" "tap=,mac=12:34:56:78:90:0b,ip=192.168.11.1,mask=255.255.255.0" "--serial" "tty" "--console" "off"

==== End cloud-hypervisor command-line ====
```

```
==== Start child stdout ====

[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x413fd0c1]
[    0.000000] Linux version 5.10.6+ (root@8f1a4822b690) (gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0, GNU ld (GNU Binutils for Ubuntu) 2.30) #52 SMP Fri Apr 9 18:32:49 UTC 2021
[    0.000000] Machine model: linux,dummy-virt
[    0.000000] earlycon: pl11 at MMIO 0x0000000009000000 (options '')
[    0.000000] printk: bootconsole [pl11] enabled
[    0.000000] efi: UEFI not found.
[    0.000000] NUMA: No NUMA configuration found
[    0.000000] NUMA: Faking a node at [mem 0x0000000080000000-0x000000009fffffff]
[    0.000000] NUMA: NODE_DATA [mem 0x9fed0680-0x9fefa63f]
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000080000000-0x000000009fffffff]
[    0.000000]   DMA32    empty
[    0.000000]   Normal   empty
[    0.000000]   Device   empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000080000000-0x000000009fffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000080000000-0x000000009fffffff]
[    0.000000] psci: probing for conduit method from DT.
[    0.000000] psci: PSCIv1.0 detected in firmware.
[    0.000000] psci: Using standard PSCI v0.2 function IDs
[    0.000000] psci: Trusted OS migration not required
[    0.000000] psci: SMC Calling Convention v1.1
[    0.000000] percpu: Embedded 21 pages/cpu s53784 r0 d32232 u86016
[    0.000000] Detected PIPT I-cache on CPU0
[    0.000000] CPU features: detected: GIC system register CPU interface
[    0.000000] CPU features: detected: Hardware dirty bit management
[    0.000000] CPU features: detected: Spectre-v4
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 129024
[    0.000000] Policy zone: DMA
[    0.000000] Kernel command line: earlycon=pl011,mmio,0x09000000
[    0.000000] Dentry cache hash table entries: 65536 (order: 7, 524288 bytes, linear)
[    0.000000] Inode-cache hash table entries: 32768 (order: 6, 262144 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 481124K/524288K available (8384K kernel code, 7702K rwdata, 2824K rodata, 1472K init, 3098K bss, 43164K reserved, 0K cma-reserved)
[    0.000000] random: get_random_u64 called from __kmem_cache_create+0x30/0x4b0 with crng_init=0
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000] rcu: 	RCU restricting CPUs from NR_CPUS=128 to nr_cpu_ids=1.
[    0.000000] 	Tracing variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 25 jiffies.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=1
[    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[    0.000000] GICv3: 224 SPIs implemented
[    0.000000] GICv3: 0 Extended SPIs implemented
[    0.000000] GICv3: Distributor has no Range Selector support
[    0.000000] GICv3: 16 PPIs implemented
[    0.000000] GICv3: CPU0: found redistributor 0 region 0:0x0000000008fd0000
[    0.000000] ITS [mem 0x08fb0000-0x08fcffff]
[    0.000000] ITS@0x0000000008fb0000: allocated 8192 Devices @81830000 (indirect, esz 8, psz 64K, shr 1)
[    0.000000] ITS@0x0000000008fb0000: allocated 8192 Interrupt Collections @81840000 (flat, esz 8, psz 64K, shr 1)
[    0.000000] GICv3: using LPI property table @0x0000000081850000
[    0.000000] GICv3: CPU0: using allocated LPI pending table @0x0000000081860000
[    0.000000] arch_timer: cp15 timer(s) running at 25.00MHz (virt).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x5c40939b5, max_idle_ns: 440795202646 ns
[    0.000001] sched_clock: 56 bits at 25MHz, resolution 40ns, wraps every 4398046511100ns
[    0.000744] Console: colour dummy device 80x25
[    0.001063] printk: console [tty0] enabled
[    0.001364] printk: bootconsole [pl11] disabled
```

</p>
</details>

Detailed error from our CI is [here](https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/blue/organizations/jenkins/cloud-hypervisor/detail/PR-2481/4/pipeline/148).

**Comment by sboeuf** [comment]
>Looks like booting with hypervisor-fw is not working on aarch64? I changed the test to use direct kernel boot to fix the issue.

@michael2012z are you okay with that?

**Comment by michael2012z** [comment]
@likebreath @sboeuf Now `hypervisor-fw` is not ready on aarch64, specifying `direct kernel path` and `--cmdline` is the only way to boot.

So that looks good.

**Review by michael2012z — APPROVED** [review]

**Pull request merged**
