### PR TITLE
vmm: Refactor slightly 'vm_create', 'vm_boot', and 'control_loop'

### PR DESCRIPTION
**Pull request by likebreath**
Couple of refactoring to ensure all handlers for `ApiRequest` in `control_loop` are
consistent and minimum. Hope it makes the code simpler and read better.

No functional changes.

Signed-off-by: Bo Chen <chen.bo@intel.com>

### CODE REVIEW

**Comment by russell-islam** [comment]
The clippy fix is done in PR https://github.com/cloud-hypervisor/cloud-hypervisor/pull/2795

**Comment by likebreath** [comment]
> The clippy fix is done in PR #2795

@russell-islam Thanks for prompting that. I believe this is much more to be done to fix the clippy issue completely. I am on it (https://github.com/likebreath/cloud-hypervisor/commits/0623/fix_beta_clippy) and will send a separate PR to fix that (hopefully later today).

**Comment by russell-islam** [comment]
> > The clippy fix is done in PR #2795
> 
> @russell-islam Thanks for prompting that. I believe this is much more to be done to fix the clippy issue completely. I am on it (https://github.com/likebreath/cloud-hypervisor/commits/0623/fix_beta_clippy) and will send a separate PR to fix that (hopefully later today).

Yes. So many. I will wait for your PR. :)

**Review by sboeuf — APPROVED** [review]
These changes look okay to me. Let's see what the CI has to say :)
We never know when moving some code around if we don't end up triggering some corner cases with weird side effect!

**Comment by sboeuf** [comment]
Please rebase your PR on latest master.

**Pull request merged**
