### PR TITLE
Fix virtio-net control queue issue

### PR DESCRIPTION
**Pull request by rbradford**
(Including Integration test.)

I have further fixes to this code but will push into a separate PR as I think we will want to cherry pick this bug fix to v22 and possibly v21.

### CODE REVIEW

**Review by sboeuf — APPROVED** [review]

**Comment by MrXinWang** [comment]
@rbradford  I suspect the arm64 CI failure maybe either because there is no ethtool in the test image, or the NIC is not named as ens4.....So feel free to gate this test case and give me and @michael2012z some time for that :))

**Comment by MrXinWang** [comment]
yep, @rbradford, would you please use this one for Arm? Thanks! `sudo ethtool -K enp0s4 rx-gro-hw off && echo success`

This gives me a pass locally:
```
running 1 test
test parallel::test_virtio_net_ctrl_queue ... ok
```

**Comment by rbradford** [comment]
> yep, @rbradford, would you please use this one for Arm? Thanks! `sudo ethtool -K enp0s4 rx-gro-hw off && echo success`
> 
> This gives me a pass locally:
> 
> ```
> running 1 test
> test parallel::test_virtio_net_ctrl_queue ... ok
> ```

Thanks @MrXinWang!

**Review by MrXinWang — APPROVED** [review]
CI gives `test parallel::test_virtio_net_ctrl_queue ... ok` so I am approving it ^^

**Comment by RamyAllam** [comment]
I tested that with KataContainers on GKE and it works properly for my use case. Thanks!

**Pull request merged**
