### PR TITLE
virtio-devices: block: Avoid panic with invalid guest address

### PR DESCRIPTION
**Pull request by likebreath**
Remove the use of 'unwrap()' that assumes the guest address for request
status is always valid, which avoid virtio-block thread panic on
malformed descriptors from the guest.

Signed-off-by: Bo Chen <chen.bo@intel.com>

### CODE REVIEW

**Review by rbradford — COMMENTED** [review]
We've been somewhat inconsistent on this in the past but...

1. If the user can do something to rectify the situation (like the kernel they've specified isn't there) then an error should be returned.
2. If the user can't do anything about it or it's a programming error then a panic is better.

In this case if this code panics the thread should exit which should trigger the whole VMM to exit? Does that not happen?

**Comment by likebreath** [comment]
> In this case if this code panics the thread should exit which should trigger the whole VMM to exit? Does that not happen?

This was reported and reproducible by the updated virtio-blocker fuzzer (#4417). I thought it is a legit bug/vulnerability as it means that a (malicious) guest workload has a reliable way to crash the virtio-block threads (and even the whole VMM as you described). Please correct me if I am mistaken.

That's why I think this code needs to be "fixed". I was not sure whether I am fixing it in the right way, but I was following more or less the same error reporting style along the code path. Any advises?

**Comment by rbradford** [comment]
> > This was reported and reproducible by the updated virtio-blocker fuzzer (#4417). I thought it is a legit bug/vulnerability as it means that a (malicious) guest workload has a reliable way to crash the virtio-block threads (and even the whole VMM as you described). Please correct me if I am mistaken.

It's a difficult situation. What happens with the panic? Does the VM shutdown or does just the thread panic leaving the VM in a broken state? What happens when you propagate an error? Does the VM shutdown or just the thread? If propagating the error still leads to the VM to shutdown then that is fine.

This is possibly the difference we have with fuzzing vs the way we run the code as device thread. In the latter we have it in a panic handler.

One of the reasons panic is preferred for things the user can't fix is if that it is a programming error we can get the line number to fix it. Blindly wrapping everything into an error loses that.

**Review by rbradford — APPROVED** [review]

**Comment by sboeuf** [comment]
>One of the reasons panic is preferred for things the user can't fix is if that it is a programming error we can get the line number to fix it. Blindly wrapping everything into an error loses that.

Isn't this true for every error in general? I mean you could argue the entire codebase should panic on errors that can be seen as unrecoverable so that it's easier to debug.

**Comment by rbradford** [comment]
> > One of the reasons panic is preferred for things the user can't fix is if that it is a programming error we can get the line number to fix it. Blindly wrapping everything into an error loses that.
> 
> Isn't this true for every error in general? I mean you could argue the entire codebase should panic on errors that can be seen as unrecoverable so that it's easier to debug.

Yes, it's something i've mentioned before - for *programming errors* not for errors where the user can do something to recover on there own.

**Comment by rbradford** [comment]
There is also another class of errors - where the guest has done something unpredictable (like this) I don't know what the best way to handle this is. I think most of the code generates an error that then gets mapped upwards. I don't think most of the time the user can do anything with that.

I would also note that programming errors are much less common in Rust due to things like `Option` and `Result` types.

**Comment by sboeuf** [comment]
> > > One of the reasons panic is preferred for things the user can't fix is if that it is a programming error we can get the line number to fix it. Blindly wrapping everything into an error loses that.
> > 
> > 
> > Isn't this true for every error in general? I mean you could argue the entire codebase should panic on errors that can be seen as unrecoverable so that it's easier to debug.
> 
> Yes, it's something i've mentioned before - for _programming errors_ - not for errors where the user can do something to recover on their own.

Should we plan some kind of sprint to go through the codebase and fix that behavior?

And about fuzzers, if we follow this approach, how can we avoid some false positive to be raised?

**Comment by rbradford** [comment]
I just added code to return an error at the the top of `process_queue_submit()` and the VM continues to run forever (although the error message is printed.) If you panic the the VM and VMM exit. I think we need to go through and make sure that we do correctly exit the VM.

The problem with the fuzzer is that it executes the code that in the VMM would run inside a panic handler.

**Comment by rbradford** [comment]
So to be clear - even though i've approved this because it makes the fuzzer happy this is actually worse behaviour for the user if the guest does program the queues wrongly. Before this change the panic would have ultimately lead to the VM and VMM exiting. With this change an error is printed out but and the thread exits but the VM and VMM remains alive (and in an inconsistent state.)

**Comment by sboeuf** [comment]
> So to be clear - even though i've approved this because it makes the fuzzer happy this is actually worse behaviour for the user if the guest does program the queues wrongly. Before this change the panic would have ultimately lead to the VM and VMM exiting. With this change an error is printed out but and the thread exits but the VM and VMM remains alive (and in an inconsistent state.)

I think we should not merge this PR based on your explanation and instead continue this discussion on #4462 to solve the problem homogeneously across all virtio devices.

**Comment by rbradford** [comment]
> > So to be clear - even though i've approved this because it makes the fuzzer happy this is actually worse behaviour for the user if the guest does program the queues wrongly. Before this change the panic would have ultimately lead to the VM and VMM exiting. With this change an error is printed out but and the thread exits but the VM and VMM remains alive (and in an inconsistent state.)
> 
> I think we should not merge this PR based on your explanation and instead continue this discussion on #4462 to solve the problem homogeneously across all virtio devices.

The problem is the correct solution in #4462 requires a lot of work (fixing all the virtio device error handling) and this PR holds back the updating of the fuzzer.

The broken handling of errors has been around in the virtio devices for a long time and this change is at least consistent with the rest of the function that generates errors that don't do very much.

**Comment by likebreath** [comment]
Merging the PR to unblock the fuzzer PR (https://github.com/cloud-hypervisor/cloud-hypervisor/pull/4417). I will work on a follow-up PR to make sure the errors propagated corrected with VMM exit gracefully as discussed from https://github.com/cloud-hypervisor/cloud-hypervisor/issues/4462#issuecomment-1209150006.

**Pull request merged**
