### PR TITLE
[WIP]The left vhost-user-blk device and backend work

### PR DESCRIPTION
**Pull request by yangzhon**
We still need add some features, like readonly, virtio-iommu and multiple queue into current vhost-user-blk device and backend.

I also added one patch and did performance tuning, and results as below
#all "write back" cache mode
#all num_queue=1 
#read/write test command in guest
  (a). time dd if=/dev/vda of=/dev/null bs=2M iflag=direct
  (b). time dd of=/dev/vda if=/dev/zero bs=2M oflag=direct count=32

#test result
(1). rust vhost user device + rust backend
read: 19.3GB/s
write: 8.67GB/s

(2). qemu vhost user device + rust backend
read: 19.08GB/s
write: 9.24GB/s

(3). qemu vhost user device + spdk
read: 8GB/s
write: 6.3GB/s

(4). qemu vhost user device + qemu backend
read: 6.6GB/s
write: 3.1GB/s

It seems the performance of rust vhost user device + rust backend is better than qemu, even qemu + spdk.   

Need to support in backend

- [x] virtio-iommu
- [x] readonly
- [x] multiple queue
- [x] performance tuning 

Need to support in device
- [ ] multiple queue

### CODE REVIEW

**Comment by yangzhon** [comment]
@slp @sboeuf 

I added some patches for vhost-user-blk backend, and tested the performance. But i found the performance data in rust vhost-user-device + rust backend is so good, and even better than qemu + spdk.

I also checked the Qemu vhost-user-device + rust backend, whose performance is almost same with rust device + rust backend.

So, it look like rust backend is better than spdk or qemu backend. Even rust backend, we only use file to read/write, which should be same to qemu backend.  

It's hard to explain this performance data. @slp, did you compare those test before? thanks.

**Comment by slp** [comment]
Yes, I did some testing and it didn't perform better than SPDK. Specially not in the current status, without EVENT_IDX nor polling.

Please avoid running benchmarks with the backend in writeback mode. That makes that a big part of the test depend on how lucky you are on hitting cached blocks. For a fair test, you'd need to modify the backends to ensure the files are opened with O_DIRECT.

On the other hand, IMHO, "dd" is not a good tool for benchmarks. Please consider using "fio" (or something similar) with "direct=1" (to bypass the guest's cache) and either "ioengine=sync" (for measuring latency) or "ioengine=libaio" (for throughput).

Also, it'd be nice pointing out the actual versions (git commit if upstream) and full command line of both the VMM and the vhost-user block backend with each result.

Thanks!

**Comment by yangzhon** [comment]
@slp 

I used the latest code plus this PR's patches to do the performance test.

The guest virtio_block.c driver only support two cache mode,
static const char *const virtblk_cache_types[] = {
    "write through", "write back"
};
The default mode of Qemu blk backend is "write through". 
cat /sys/block/vda/cache_type
write through

I also tried to add options.custom_flags(O_DIRECT) into backend, but which will make detect_image_type() panic during the binary run.
let image_id = build_disk_image_id(&PathBuf::from(&image_path));
let image_type = **qcow::detect_image_type(&raw_img).unwrap();**
let mut image = match image_type {
        ImageType::Raw => Box::new(vm_virtio::RawFile::new(raw_img)) as Box<dyn DiskFile>,
        ImageType::Qcow2 => Box::new(QcowFile::from(raw_img).unwrap()) as Box<dyn DiskFile>,
};

The panic as below:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ReadingHeader(Os { code: 22, kind: InvalidInput, message: "Invalid argument" })', src/libcore/result.rs:1051:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace. 

thanks.

**Comment by slp** [comment]
> The panic as below:
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ReadingHeader(Os { code: 22, kind: InvalidInput, message: "Invalid argument" })', src/libcore/result.rs:1051:5
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

This happens because O_DIRECT imposes some alignment restrictions on I/O requests. I created PR #490 for adding direct mode support in vhost_user_blk, perhaps you can use it for your tests.

**Comment by sboeuf** [comment]
@yangzhon 
As discussed offline, it'd be nice to focus on only one feature at a time and enable them step by step through separate PRs.
You can open an issue listing all the missing features and refer this issue from each PR you will open.
Please make sure you update the title too, as it's unclear what the PR is doing with the current one.

**Comment by sameo** [comment]
> @yangzhon
> As discussed offline, it'd be nice to focus on only one feature at a time and enable them step by step through separate PRs.
> You can open an issue listing all the missing features and refer this issue from each PR you will open.
> Please make sure you update the title too, as it's unclear what the PR is doing with the current one.

@yangzhon Also could you please make sure the issue(s) are added to the 0.5.0 release project?

**Comment by yangzhon** [comment]
> > @yangzhon
> > As discussed offline, it'd be nice to focus on only one feature at a time and enable them step by step through separate PRs.
> > You can open an issue listing all the missing features and refer this issue from each PR you will open.
> > Please make sure you update the title too, as it's unclear what the PR is doing with the current one.
> 
> @yangzhon Also could you please make sure the issue(s) are added to the 0.5.0 release project?

@sameo @sboeuf ,

Yes, I will split the PR into sub-PRs to submit again. By the way, since the virtio-iommu SPEC is still not fixed now, and i will send readonly and multi-queue support only. thanks for reminder.

**Comment by sboeuf** [comment]
@yangzhon 
>By the way, since the virtio-iommu SPEC is still not fixed now, and i will send readonly and multi-queue support only

Yes that makes sense.

**Comment by yangzhon** [comment]
There is one new PR #563 to track this, so close this one. thanks.

**Pull request closed without merging**
