### PR TITLE
Fix an undefined behaviour in offset__of

### PR DESCRIPTION
**Pull request by liuw**
I found this undefined behaviour while going through unsafe blocks.

### CODE REVIEW

**Comment by liuw** [comment]
I have not seen a minimum required version of Rust in the in-tree documents, but this change effectively bumps(?) the minimum required version to 1.51 because of `addr_of`

**Review by likebreath — APPROVED** [review]
Good to learn some unsafe/safety rules around `MaybeUninit`. Thanks @liuw

**Comment by rbradford** [comment]
> I have not seen a minimum required version of Rust in the in-tree documents, but this change effectively bumps(?) the minimum required version to 1.51 because of `addr_of`

That's absolutely fine. In the past we've said that we only really support building with the latest version (which is in the Dockerfile / GitHub actions.) Anything older might work but is not what we support.

**Review by rbradford — APPROVED** [review]

**Review by MrXinWang — APPROVED** [review]

**Comment by michael2012z** [comment]
It's good to know that `addr_of` was introduced. It makes the code more graceful. 

Thank you for improving the code and the comment.

**Review by michael2012z — APPROVED** [review]

**Pull request merged**
