### PR TITLE
Unified binary -- part 6

### PR DESCRIPTION
**Pull request by liuw**
This PR rework the code to make use of the new vfio-ioctls APIs.

The vfio-ioctls PR is still pending. https://github.com/rust-vmm/vfio/pull/9

This however showcases what the code looks like with the new APIs.

Cc @michael2012z @MrXinWang @jinankjain @russell-islam

### CODE REVIEW

**Comment by liuw** [comment]
If people are happy with the change I can split out all but the last patch to a separate PR.

**Review by sboeuf — APPROVED** [review]
LGTM

**Comment by liuw** [comment]
This PR now points to the upstream vfio-ioctls crate instead of my fork.

**Review by rbradford — APPROVED** [review]

**Comment by liuw** [comment]
@michael2012z @MrXinWang Before I merge this PR I would really like to get an approval from ARM developers -- the code is correct but just in case you disagree with the way it is done.

**Review by likebreath — APPROVED** [review]
@liuw Thanks for the good work. I can always learn something new from your PR. This time it is about using trait `Any` for runtime reflection in rust.

**Review by michael2012z — APPROVED** [review]
@liuw The new code looks really good. Thanks.

**Pull request merged**
