### PR TITLE
hypervisor: mshv: Add new memory region flag

### PR DESCRIPTION
**Pull request by jinankjain**
GPA_MAP_ADJUSTABLE suggests hypervisor to adjust GPA permissions as required.

### CODE REVIEW

**Review by likebreath — APPROVED** [review]
My rubber stamp. @russell-islam PTAL

**Comment by russell-islam** [comment]
@jinankjain  I want to understand why the flag USER_MEMORY_REGION_ADJUSTABLE is needed now? I believe we did not have this flag during our last PP release.

**Comment by jinankjain** [comment]
> @jinankjain I want to understand why the flag USER_MEMORY_REGION_ADJUSTABLE is needed now? I believe we did not have this flag during our last PP(Public Preview) release.

That was kind of hack, this is a cleaner version of that. If we don't add USER_MEMORY_REGION_ADJUSTABLE then there is an issue when we convert mshv_mem_region to user_mem_region and back again to mshv_mem_region. The the flag will get lost in translation.

**Review by russell-islam — APPROVED** [review]

**Review by rbradford — APPROVED** [review]
@likebreath has given his rslgtm so fine with me!

**Pull request merged**
