### PR TITLE
tests: Enable 'test_vfio_user'

### PR DESCRIPTION
**Pull request by likebreath**
Signed-off-by: Bo Chen <chen.bo@intel.com>

### CODE REVIEW

**Comment by likebreath** [comment]
@rbradford Can you please make the CI run on this PR periodically, so that we can see how stable the `test_vfio_user` is? 

Looks like the test somehow is less flaky...  My experiments with my dev machine and an Azure VM were all passed where I ran the `test_vfio_user` with `dev_cli.sh` for 100 times repeatedly. Also, the PR passed the CI 4 times with manual forced push.

I haven't figured what makes the difference. I also did the same experiment with an earlier commit of CH based on your PR #3611 (which supposed to be failing), but `test_vfio_user` also passed 100 times consecutively. I can't think of any moving parts besides the dev container being used (e.g. the tag "latest" of dev container image now is different).  Any thoughts?

**Comment by rbradford** [comment]
https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/job/PR%203793%20periodic/

**Comment by sboeuf** [comment]
>I can't think of any moving parts besides the dev container being used (e.g. the tag "latest" of dev container image now is different). Any thoughts?

That's a good guess IMO as it could be the reason. Some libraries might have been updated, causing the test to be stable.

**Comment by sboeuf** [comment]
Looking at the different runs, it seems it's less reproducible but still happens 10% of the time.

**Comment by rbradford** [comment]
@likebreath FYI, all the fails are exclusively on musl builds.

**Comment by likebreath** [comment]
PR updated with seccomp filter disabled. So far no failures. I tried to reproduce the failure locally with musl build, but both my dev machine and the Azure instance passed 100 iterations (using 8b809d92fb46739f860745780402241f409408b5 w/o seccomp disabled). 

Looking at the CI history so far (with 45 CI jobs), we got 5 failures in total: 
* `x86_64` workers got 2 failures  ([job 9](https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/blue/organizations/jenkins/cloud-hypervisor/detail/PR-3793/9/pipeline/193/) and [job 19](https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/blue/organizations/jenkins/cloud-hypervisor/detail/PR-3793/19/pipeline/)). Both failures are on musl build and caused by `assertion failed: exec_host_command_status(\"/usr/local/bin/spdk-nvme/rpc.py nvmf_create_transport -t VFIOUSER\").success()`. Hopefully we will have more information about this failure from `nvmf_tgt` output with its debug build (not failed after `debug-build` is enabled).
* The `aarch64` worker got 3 failures ([job 10](https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/blue/organizations/jenkins/cloud-hypervisor/detail/PR-3793/10/pipeline/133), [job 27](https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/blue/organizations/jenkins/cloud-hypervisor/detail/PR-3793/27/pipeline/135/), and [job 38](https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/blue/organizations/jenkins/cloud-hypervisor/detail/PR-3793/38/pipeline/160/)). They are all reported as `ssh` failures to the guest but with different commands, e.g. `"lsblk | grep nvme0n1 | grep -c 128M"` and `"sudo reboot"`.

**Comment by likebreath** [comment]
Close the PR temporally to stop the period CI, and will reopen next week.

**Comment by likebreath** [comment]
Three more failures on `test_vfio_user` between CI job 46 to 75 (for the past 24 hours):

* Two failures on `x86_64` workers ([job 47](https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/blue/organizations/jenkins/cloud-hypervisor/detail/PR-3793/47/pipeline/) and [job 57](https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/blue/organizations/jenkins/cloud-hypervisor/detail/PR-3793/57/pipeline/)), and both failed in a different way comparing with previous failures on `x86_64` : failed on the `gnu` libc build, and both are due to ssh command failures (either "`sudo reboot`" or "`lsblk | grep nvme0n1 | grep -c 128M`").
* One failure on the `aarch64` worker ([job 66](https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/blue/organizations/jenkins/cloud-hypervisor/detail/PR-3793/66/pipeline/165/)): due to timeout from `wait_vm_boot()` (after successful ssh command `sudo reboot`). 

Two unrelated failures on `test_reboot` from [job 71](https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/blue/organizations/jenkins/cloud-hypervisor/detail/PR-3793/71/pipeline/) and `test_macvtap_hotplug` from [job 74](https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/blue/organizations/jenkins/cloud-hypervisor/detail/PR-3793/74/pipeline/).

**Pull request closed without merging**
