### PR TITLE
Enable guest to report free pages through virtio-balloon

### PR DESCRIPTION
**Pull request by sboeuf**
Adding a new parameter free_page_reporting=on|off to the balloon device
so that we can enable the corresponding feature from virtio-balloon.

Running a VM with a balloon device where this feature is enabled allows
the guest to report pages that are free from guest's perspective. This
information is used by the VMM to release the corresponding pages on the
host.

### CODE REVIEW

**Review by rbradford — APPROVED** [review]

**Comment by rbradford** [comment]
@sboeuf Why would we not want to turn this on by default if the guest supports it?

**Comment by sboeuf** [comment]
> @sboeuf Why would we not want to turn this on by default if the guest supports it?

Well by enabling this by default, and assuming the guest supports it, depending on the workload, the guest might send a lot of requests to the VMM, which might cause a slight performance drop since you're using the VMM more. For a user who doesn't want this feature at all, it'd be unfortunate if they had to experience this potential performance issue, don't you think?

**Comment by rbradford** [comment]
Can't we know if the guest supports it from the virtio features it acks? My worry is that the more features you expose the less discoverable they are.

**Comment by sboeuf** [comment]
>Can't we know if the guest supports it from the virtio features it acks?

Yes of course we can know that from the acknowledgement from the guest.

>My worry is that the more features you expose the less discoverable they are.

I'm not following here, can you please elaborate?

**Comment by rbradford** [comment]
> > My worry is that the more features you expose the less discoverable they are.
> 
> I'm not following here, can you please elaborate?

The more runtime knobs you have the more tweaks you might have to make for your use case. Our documentation is already lacking for the options we currently have.

**Comment by sboeuf** [comment]
>The more runtime knobs you have the more tweaks you might have to make for your use case. Our documentation is already lacking for the options we currently have.

Gotcha. Well the first thing we should do is to improve our documentation by adding something about `balloon`.
Here it is #3807

**Pull request merged**
