### PR TITLE
AArch64: Support CPU topology (ACPI and Device Tree)

### PR DESCRIPTION
**Pull request by MrXinWang**
This PR adds the device tree and ACPI support for AArch64 CPU topology. Related ACPI integration test cases are also added.

### CODE REVIEW

**Comment by MrXinWang** [comment]
Hi @rbradford @sboeuf, do you have any idea about why the `test_macvtap` failed in the CI machine? It seems that this case passed on my local machine and I doubt this PR has related with the network...


```
running 1 test
2: guestmacvtap0@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 500
    link/ether 12:34:56:78:90:01 brd ff:ff:ff:ff:ff:ff
test tests::parallel::test_macvtap ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 55 filtered out; finished in 9.31s
```

**Comment by rbradford** [comment]
I've reverted the enabling of the integration tests to see if we've got some weird test numbering / clash going on...

**Comment by MrXinWang** [comment]
> I've reverted the enabling of the integration tests to see if we've got some weird test numbering / clash going on...

Thank you very much for your time :)))

**Comment by rbradford** [comment]
Not running the newly enabled tests made the integration tests pass on aarch64.

**Comment by MrXinWang** [comment]
> Not running the newly enabled tests made the integration tests pass on aarch64.

Then it seems that some strange things are going on......(I assume these test cases are independent between each other?)

**Comment by rbradford** [comment]
I also tried limiting the number of simultaneous tests to 40 but the test still failed then. So this something to do with the the number of tests rather than the number of tests running at once.

**Comment by rbradford** [comment]
> I also tried limiting the number of simultaneous tests to 40 but the test still failed then. So this something to do with the the number of tests rather than the number of tests running at once.

Actually let's try with a really low simultaneous number first (10) before jumping to a conclusion.

**Comment by rbradford** [comment]
So I got this to pass by setting the number of test threads to 16 (fails with 20.) I'm not happy with this solution to the problem though...

**Comment by sboeuf** [comment]
>So I got this to pass by setting the number of test threads to 16 (fails with 20.) I'm not happy with this solution to the problem though...

I agree this is not great :-/
What's the alternative? Running the CPU topology test in `sequential` for `aarch64`?

**Comment by MrXinWang** [comment]
> > So I got this to pass by setting the number of test threads to 16 (fails with 20.) I'm not happy with this solution to the problem though...
> 
> I agree this is not great :-/
> What's the alternative? Running the CPU topology test in `sequential` for `aarch64`?

Please let us try some different things locally to identify the issue. Today I tried to run all integration test cases in parallel without limiting the test threads (on the same type of machine as the CI machine). All cases passed without problem. Therefore I think maybe more investigation is needed.

**Comment by MrXinWang** [comment]
Hi @rbradford! So I added the ACPI code and 3 more test cases to cover the ACPI CPU topology on arm64, and it seems that without your patch (the limitation of test thread one), the arm64 CI can pass now.

Is there a method to automatically retrigger the CI for some hours? I kinda hope to see if the arm64 CI is flaky before we merge this PR...Thank you!

**Comment by rbradford** [comment]
@MrXinWang We have the ability to trigger it periodically which I have enabled. You should see it building every 2 hours.

**Comment by MrXinWang** [comment]
Perfect! Thanks @rbradford. Then I will leave this PR for a day and let's hope all the best.

Meanwhile @sboeuf @rbradford @michael2012z please take a look at the PR and comment if you have any concerns. Thanks!

**Comment by michael2012z** [comment]
I have just one thing to discuss, it's about the test cases setting: Totally 6 cases (out of 58) are set for cpu-topology. Are they all necessary? Are we testing too much for a single feature? Coverage test should be done in unit test, not integration test.

**Comment by MrXinWang** [comment]
Yeah maybe we need some discussions here.

My point is, 3 of 6 cases are for testing the device tree, and the other 3 is for testing ACPI.

@rbradford my understanding of the original test case design is to split 2 cases - `thread per core = 1` and `thread per core > 1`. If so, do you think it is safe to only use `test_cpu_topology_262` for covering both? Thanks!

**Comment by michael2012z** [comment]
How about setting the cpu-topology cases in this way?
- Keep 3 cases, do not add any new case;
- Test  `test_cpu_topology_421` and `test_cpu_topology_142` with FDT;
- Test `test_cpu_topology_262` with ACPI;
- No change on X86.

**Comment by MrXinWang** [comment]
> How about setting the cpu-topology cases in this way?
> * Test `test_cpu_topology_262` with ACPI;

Then from my understanding we can never test the `else` condition of below code.

```rust
if threads_per_core > 1 {
    let core_hierarchy_node = ProcessorHierarchyNode {
        r#type: 0,
        length: 20,
        reserved: 0,
        flags: 0x2,
        parent: cluster_offset as u32,
        acpi_processor_id: core_idx as u32,
        num_private_resources: 0,
    };
    pptt.append(core_hierarchy_node);

    for _thread_idx in 0..threads_per_core {
        let thread_hierarchy_node = ProcessorHierarchyNode {
            r#type: 0,
            length: 20,
            reserved: 0,
            flags: 0xE,
            parent: core_offset as u32,
            acpi_processor_id: uid as u32,
            num_private_resources: 0,
        };
        pptt.append(thread_hierarchy_node);
        uid += 1;
    }
} else {
    let thread_hierarchy_node = ProcessorHierarchyNode {
        r#type: 0,
        length: 20,
        reserved: 0,
        flags: 0xA,
        parent: cluster_offset as u32,
        acpi_processor_id: uid as u32,
        num_private_resources: 0,
    };
    pptt.append(thread_hierarchy_node);
    uid += 1;
}

```

**Review by rbradford — APPROVED** [review]

**Review by michael2012z — APPROVED** [review]

**Pull request merged**
