### PR TITLE
Add missing backslash to example code in README.md

### PR DESCRIPTION
**Pull request by zbleness**

### CODE REVIEW

**Review by likebreath — COMMENTED** [review]
Thank you for the contribution. The changes look good. 

Would you please follow the patch format described https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/CONTRIBUTING.md#patch-format? More specifically, you will need to add a signed-off-by footer and refine the commit subject, say "README.md: Add missing backslash to example code".

**Comment by zbleness** [comment]
Done @likebreath!

Hope you can use my weird (nevertheless fully functional) e-mail address.

**Review by sboeuf — COMMENTED** [review]
Looking good,  but you need to replace:
```
Signed-off-by: <77726616+zbleness@users.noreply.github.com>
```
with
```
Signed-off-by: zbleness <77726616+zbleness@users.noreply.github.com>
```

**Comment by zbleness** [comment]
Right, done (good catch @likebreath) .

**Review by sboeuf — APPROVED** [review]

**Pull request merged**
