### PR TITLE
.github: Use 1.60 toolchain consistently in release process

### PR DESCRIPTION
**Pull request by rbradford**
Signed-off-by: Rob Bradford <robert.bradford@intel.com>

### CODE REVIEW

**Comment by rbradford** [comment]
@sboeuf v24.0-test tag including this commit: https://github.com/cloud-hypervisor/cloud-hypervisor/runs/6600798588

**Comment by rbradford** [comment]
Weird..duplicated PR. :shrug:

**Comment by sboeuf** [comment]
Yes super weird given I've already merged the other one...

**Comment by sboeuf** [comment]
@rbradford do I need to tag on the latest commit from `main` to get the release to work? Meaning the tag won't be on the release commit.

**Pull request closed without merging**
