### PR TITLE
hypervisor: mshv: Add missing function prototypes for aarch64

### PR DESCRIPTION
**Pull request by jinankjain**

### CODE REVIEW

**Review by liuw — APPROVED** [review]

**Review by likebreath — COMMENTED** [review]
If building `mshv` (and maybe `sev_snp` and `igvm`) is something you want to support on `aarch64`, it is better to enable the corresponding GH workflows, such as: https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/.github/workflows/quality.yaml#L90-L120

**Comment by likebreath** [comment]
> > If building `mshv` (and maybe `sev_snp` and `igvm`) is something you want to support on `aarch64`, it is better to enable the corresponding GH workflows, such as: https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/.github/workflows/quality.yaml#L90-L120
> 
> Yes that's the plan once I get it to build I would enable it in the build pipeline.

Good to know. I'd suggest to send a single (maybe big with many commits) when you get it build, and enable the corresponding workflow in the same PR. In this way, we can have the changes being tested. Of course you can enable the features one by one with different PRs.

**Comment by jinankjain** [comment]
> > > If building `mshv` (and maybe `sev_snp` and `igvm`) is something you want to support on `aarch64`, it is better to enable the corresponding GH workflows, such as: https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/.github/workflows/quality.yaml#L90-L120
> > 
> > 
> > Yes that's the plan once I get it to build I would enable it in the build pipeline.
> 
> Good to know. I'd suggest to send a single (maybe big with many commits) when you get it build, and enable the corresponding workflow in the same PR. In this way, we can have the changes being tested. Of course you can enable the features one by one with different PRs.

I need to cleanup few of the dependent crates as well. Let me submit PRs for that as well. That's why I haven't submitted a single PR for everything.

**Comment by likebreath** [comment]
> > > > If building `mshv` (and maybe `sev_snp` and `igvm`) is something you want to support on `aarch64`, it is better to enable the corresponding GH workflows, such as: https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/.github/workflows/quality.yaml#L90-L120
> > > 
> > > 
> > > Yes that's the plan once I get it to build I would enable it in the build pipeline.
> > 
> > 
> > Good to know. I'd suggest to send a single (maybe big with many commits) when you get it build, and enable the corresponding workflow in the same PR. In this way, we can have the changes being tested. Of course you can enable the features one by one with different PRs.
> 
> I need to cleanup few of the dependent crates as well. Let me submit PRs for that as well. That's why I haven't submitted a single PR for everything.

Sure, no problem. My main point is that we want to have any changes being tested by the workflow. The earlier the better.

**Pull request merged**
