### PR TITLE
Update KVM's required capability lists

### PR DESCRIPTION
**Pull request by liuw**
I was enumerating the required capabilities but found the lists incomplete.

No functional change intended with this PR.

### CODE REVIEW

**Comment by liuw** [comment]
The nightly failures are unrelated to the changes here.

**Review by rbradford — APPROVED** [review]
Great change - thanks!

**Comment by rbradford** [comment]
@liuw I think the list of required capabilities may be too aggressive - I can't recall what host OS the VFIO, etc, workers use but I think one of the capability checks is failing. Since these systems successfully run the CI I am concluding that the list of capability checks may be too aggressive for what is needed in practice.

**Comment by rbradford** [comment]
I tested on focal and found `EnableCap` and `SetGuestDebug` are not available on the focal kernel. This is not because the functionality was not implemented merely they are missing from the capability checking code see https://github.com/torvalds/linux/commit/b9b2782cd55aaf5a65573df99376cf391941cb66 and 
https://github.com/torvalds/linux/commit/127770ac0d043435375ab86434f31a93efa88215

**Comment by liuw** [comment]
> I tested on focal and found `EnableCap` and `SetGuestDebug` are not available on the focal kernel. This is not because the functionality was not implemented merely they are missing from the capability checking code see [torvalds/linux@b9b2782](https://github.com/torvalds/linux/commit/b9b2782cd55aaf5a65573df99376cf391941cb66) and [torvalds/linux@127770a](https://github.com/torvalds/linux/commit/127770ac0d043435375ab86434f31a93efa88215)

That's true. I tested locally. KVM_CAP_DEVICE_CTRL, while documented as applicable to all architecture, was only made available to x86 in late 2023.

**Comment by up2wing** [comment]
> @liuw I think the list of required capabilities may be too aggressive - I can't recall what host OS the VFIO, etc, workers use but I think one of the capability checks is failing. Since these systems successfully run the CI I am concluding that the list of capability checks may be too aggressive for what is needed in practice.

Agree.

In my opinion, now that we have declared the minimal version of host OS[1], maybe we don't need to do so much extention check. Another point is that kvm doesn't support batch check, each check needs an iotcl, which may cost some time, although that's very insignificant :)

1. https://github.com/cloud-hypervisor/cloud-hypervisor?tab=readme-ov-file#host-os

**Review by up2wing — APPROVED** [review]

**Review by up2wing — APPROVED** [review]

**Review by up2wing — APPROVED** [review]

**Comment by liuw** [comment]
I shrunk the list and put in a comment in the check functions. Let me know what you think.

**Review by rbradford — APPROVED** [review]

**Pull request merged**
