### PR TITLE
Switch to the cloud-hypervisor vfio-ioctls crate

### LINKED ISSUE #377: Evaluate rust-vmm vfio-ioctls initial PR
See:
https://github.com/rust-vmm/vfio-ioctls/pull/1

We need to verify that those changes still work with our implementation.

### PR DESCRIPTION
**Pull request by arronwy**
This PR passed local test_vfio integration test, other integration test did not test yet.

Fixes #377

### CODE REVIEW

**Comment by sboeuf** [comment]
@arronwy thanks! Could you please point to the `ch` branch instead of `dragonball`. It contains the exact same things, but it's more appropriate for the naming.

**Comment by arronwy** [comment]
> @arronwy thanks! Could you please point to the `ch` branch instead of `dragonball`. It contains the exact same things, but it's more appropriate for the naming.

Thanks, updated to ch branch now:)

**Comment by rbradford** [comment]
@arronwy You need to run `cargo fmt`

**Comment by arronwy** [comment]
> @arronwy You need to run `cargo fmt`

Thanks Rob, I updated with cargo fmt local check passed now:)

**Pull request merged**
