### PR TITLE
Windows CI integration testing

### PR DESCRIPTION
**Pull request by rbradford**
Signed-off-by: Rob Bradford <robert.bradford@intel.com>

### CODE REVIEW

**Comment by rbradford** [comment]
@liuw @weltling I'm going to need you guys to take this over. @sboeuf can help you if necessary.

**Comment by liuw** [comment]
How does the guest get its IP address given in the SSH command?

**Comment by weltling** [comment]
The image is configured to receive the IP through [SAC](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/docs/windows.md#basic-networking) The current patch passes `--net tap=`, so the automatically created TAP device will be `192.168.249.1` and the guest has `192.168.249.2` recorded through SAC and knows the tap will be its gateway. One can explicitly configure this using netsh, but having it set in SAC seems to be enough.

Regarding teh crash issue, wondering what `ACPI_BIOS_ERROR` is supposed to be. Perhaps we should check that the OVMF bins are suitable?

Thanks.

**Comment by weltling** [comment]
Ah, and also - i never ran it under Docker, and i never tried musl. These might be points, too. Thanks.

**Comment by liuw** [comment]
FTR the failure here is specific to the CI setup. The CI runs on Azure. KVM runs nested on top of Hyper-V. Apparently enabling KVM's Hyper-V emulation when there is really a Hyper-V underneath doesn't end well.

We don't have a solution yet. We will need to figure out where exactly it fails. The solution can be as simple as changing CPUID bits a bit more or as difficult as "this can only be solved by fixing KVM / Hyper-V".

All in all I think the setup this CI has is not representative of real world deployment, so we may end up just getting a baremetal KVM installation specifically for Windows test can call it a day.

**Comment by weltling** [comment]
ditto.

**Comment by weltling** [comment]
Got an update on this. It might be, that the issue is not directly related to the nested virtualization. The same failure  is observed under Ubuntu 20.04 with mainline kernel 5.8.14 on the bare metal x3950 with AMD CPU. It is not clear yet, of the error is exactly same, as there's no backtrace, but it throws ACPI_BIOS_ERROR, too. I'll update on this yet when i've more info.

Thanks

**Comment by sboeuf** [comment]
@liuw 
>All in all I think the setup this CI has is not representative of real world deployment, so we may end up just getting a baremetal KVM installation specifically for Windows test can call it a day.

Having a dedicated machine for testing Windows would be fine. We already have such setup for ARM architecture and SGX feature.

**Comment by liuw** [comment]
> 
> 
> @liuw
> 
> > All in all I think the setup this CI has is not representative of real world deployment, so we may end up just getting a baremetal KVM installation specifically for Windows test can call it a day.
> 
> Having a dedicated machine for testing Windows would be fine. We already have such setup for ARM architecture and SGX feature.

That's cool. We can perhaps just use the SGX test machine for Windows tests too.

**Comment by sameo** [comment]
> FTR the failure here is specific to the CI setup. The CI runs on Azure. KVM runs nested on top of Hyper-V. Apparently enabling KVM's Hyper-V emulation when there is really a Hyper-V underneath doesn't end well.
> 

Do we have some details on that one? what's failing with that setup?

> We don't have a solution yet. We will need to figure out where exactly it fails. The solution can be as simple as changing CPUID bits a bit more or as difficult as "this can only be solved by fixing KVM / Hyper-V".
> 

CPUID tweaking is ok. The latter is not a road we'd want to follow, I think :-)

> All in all I think the setup this CI has is not representative of real world deployment, so we may end up just getting a baremetal KVM installation specifically for Windows test can call it a day.

Definitely agree. And that would be closer to a real life setup as well.

**Comment by liuw** [comment]
> 
> 
> > FTR the failure here is specific to the CI setup. The CI runs on Azure. KVM runs nested on top of Hyper-V. Apparently enabling KVM's Hyper-V emulation when there is really a Hyper-V underneath doesn't end well.
> 
> Do we have some details on that one? what's failing with that setup?
> 

When I run Windows on top of an Azure VM I have, it is failing the same way like in the CI.

Basically Windows kernel got BSOD with ACPI_BIOS_ERROR 0xA5 and kept rebooting.

```
<INSTANCE CLASSNAME="BLUESCREEN">
<PROPERTY NAME="STOPCODE" TYPE="string"><VALUE>"0xA5"</VALUE></PROPERTY>
</INSTANCE>
</BP>

!SAC>
ACPI_BIOS_ERROR
```

And from Cloud Hypervisor's PoV, the guest kept touching some Virtio queues that are not yet ready.

@weltling 's report is interesting too, but I don't have any logs.

**Comment by liuw** [comment]
@sameo @rbradford @sboeuf 

As far as I can tell, to use the SGX test machine all I need to do is to specify ` agent { node { label 'bionic-sgx' } } ` in Jenkinsfile.

That looks rather easy to try out.

I'm wondering if I should just make the change and push to @rbradford 's branch to trigger the pipeline again? How do we proceed here?

**Review by sboeuf — CHANGES_REQUESTED** [review]
Just marking this as needed changes since we don't want to merge this PR by mistake.

**Review by sboeuf — APPROVED** [review]

**Comment by sboeuf** [comment]
@weltling @liuw @sameo Please have a look. I have completely fixed the PR now. The Windows CI is passing along with regular CI. I think this is ready to be merged.

**Review by sameo — APPROVED** [review]

**Review by liuw — APPROVED** [review]

**Pull request merged**
