### PR TITLE
docs: Add virtiofs root howto

### PR DESCRIPTION
**Pull request by iggy**
Add a quick HowTo for using a virtiofs root filesystem in a
cloud-hypervisor guest.

Signed-off-by: Iggy Jackson <iggy@theiggy.com>

### CODE REVIEW

**Review by sboeuf — COMMENTED** [review]
@iggy thanks for the PR :)
Have you seen the virtio-fs related documentation in `docs/fs.md`? I think it'd be more appropriate to append your documentation to the existing one rather than creating a separate document.

**Comment by iggy** [comment]
I don't have a problem with that. I was worried it was going to get quite long if added instructions for making other distro root filesystems. I'll have to play around with the end bit some too, or maybe just drop it.

**Comment by rbradford** [comment]
@iggy I think it's cool you've written this document. I've been pondering for a while whether we ought to move most of our documentation, especially stuff focussed on the user side to the wiki. I think your contributed guide would fit in there perfectly.

**Comment by rbradford** [comment]
(Also the wiki might make it easier to keep it updated / get it more visibility.)

**Comment by iggy** [comment]
I'm cool with either way (moving to `docs/fs.md` or just throwing it in the wiki). Whatever you guys think is most appropriate. Currently, I can see the wiki tab for the repo, but when I click on it, it just redirects to the main repo url. Don't know if that's because there aren't any wiki pages currently or if it needs some privileges.

**Comment by likebreath** [comment]
> Don't know if that's because there aren't any wiki pages currently or if it needs some privileges.

I believe the problem is that write-access to the repos is required to edit the Wiki (with the default setting). Quote from [GH's document](https://docs.github.com/en/github/building-a-strong-community/about-wikis):

`By default, only people with write access to your repository can make changes to wikis, although you can allow everyone on GitHub to contribute to a wiki in a public repository. For more information, see "Changing access permissions for wikis".`

Looks like the only alternative setting is allowing all GH users to edit the Wiki. @rbradford @sboeuf Any thoughts on how to move forward?

**Review by rbradford — APPROVED** [review]

**Comment by rbradford** [comment]
Let's merge for now as move to the wiki subsequently.

**Review by sboeuf — APPROVED** [review]

**Pull request merged**
