### PR TITLE
tests: Port various integration tests to new methodology

### PR DESCRIPTION
**Pull request by likebreath**
This patch ported many tests to the new methodology, where the guest log
will be printed only when the test is failing.

Things to finish in follow-up PRs:

1. Special tests not ported yet include: test_reboot,
test_bzimage_reboot, test_serial_null(), test_serial_tty(),
test_serial_file(), test_virtio_console(), test_console_file(),
and test_simple_launch().

2. Few direct calls to 'Command::new(clh_command("cloud-hypervisor"))',
which is still printing the guest console

Signed-off-by: Bo Chen <chen.bo@intel.com>

### CODE REVIEW

**Comment by likebreath** [comment]
@rbradford This is a WIP PR.  As mentioned in the todo list above, I will keep working on it tomorrow. Any quick comments or advises, please let me know.

Porting the tests are not taking much time, but somehow I got a strange issue:

The `test_simple_launch` works fine with the current `partial-ported` version, where the `capture_output()` is not enabled for the `GuestCommand`. However, it would simple fail on the first assertion (as a result of `ssh` timeout I guess), if the `capture_output()` is enabled/used..

**Comment by rbradford** [comment]
I suggest you publish one PR with "fully ported" version of the ones you know work leaving the ones that have some issues to one side.

**Comment by rbradford** [comment]
I suggest you publish one PR with "fully ported" version of the ones you know work leaving the ones that have some issues to one side.

**Comment by likebreath** [comment]
> I suggest you publish one PR with "fully ported" version of the ones you know work leaving the ones that have some issues to one side.

@rbradford Sounds good. It looks like the CI is passing with all ported tests (while few are failing on my local machine). I can certainly refine this PR and make it merge-ready.

Two quick questions: 1) do you want me to squash the commits into one or keep the PR as two commits (one for real porting change, and the other for fixing formatting)? 2) do you want to keep the current TODO list in the commit message or make the message cleaner?

**Comment by rbradford** [comment]
You should fix the formatting in the same commit when you changed it. If you want to split it should be across different tests.

**Comment by likebreath** [comment]
@rbradford @sboeuf PTAL. I will keep working on the ones left.

**Review by rbradford — APPROVED** [review]
:+1:

**Review by sboeuf — APPROVED** [review]

**Pull request merged**
