### PR TITLE
Stable backport fixes for v37.x

### PR DESCRIPTION
**Pull request by likebreath**
* https://github.com/cloud-hypervisor/cloud-hypervisor/pull/6134
* https://github.com/cloud-hypervisor/cloud-hypervisor/pull/6141
* https://github.com/cloud-hypervisor/cloud-hypervisor/pull/6106
* https://github.com/cloud-hypervisor/cloud-hypervisor/pull/6146
* https://github.com/cloud-hypervisor/cloud-hypervisor/pull/6062
* https://github.com/cloud-hypervisor/cloud-hypervisor/pull/6080
* https://github.com/cloud-hypervisor/cloud-hypervisor/pull/6091
* https://github.com/cloud-hypervisor/cloud-hypervisor/pull/6095
* https://github.com/cloud-hypervisor/cloud-hypervisor/pull/6196

### CODE REVIEW

**Comment by likebreath** [comment]
@rbradford I think again about how we should ran the complete CI workers on stable branches, and I decided to go with requiring a MQ (like what we have for main branch).  I now believe we won't need the flexibility to rerun individual workers that are failing, since most of the failures for stable branches will require more backporting patches and hence a push (that will run the complete CI again anyway).

With that, the PR is ready for review. One note is that due to backporting #6134, the live-upgrade between v37.0 to v37.1 will be broken.

**Comment by rbradford** [comment]
> With that, the PR is ready for review. One note is that due to backporting #6134, the live-upgrade between v37.0 to v37.1 will be broken.

Eeek. I think that is a real shame - this is about kvm_xsave - right? We should look at the length of the serialised data and if it is 4KiB then manually deserialise that part into the field. (This should be a change on main and backported.)

KVM_XSAVE2 ioctl looks interesting as it handles the variable size part.

**Comment by likebreath** [comment]
> > With that, the PR is ready for review. One note is that due to backporting #6134, the live-upgrade between v37.0 to v37.1 will be broken.
> 
> Eeek. I think that is a real shame - this is about kvm_xsave - right? We should look at the length of the serialised data and if it is 4KiB then manually deserialise that part into the field. (This should be a change on main and backported.)
> 

Yes, the old `xsave` field is 4KiB. I guess we will need to implement a custom `deserilizer` to do it? Do you want to give it try?

> KVM_XSAVE2 ioctl looks interesting as it handles the variable size part.

Right. The new struct `kvm_xsave` appends a flexible array member to the old struct definition to support such case. We will also need to support sterilization between the fixed size and variable size of the `XsaveState` to avoid live-upgrade break.

**Comment by rbradford** [comment]
> > > With that, the PR is ready for review. One note is that due to backporting #6134, the live-upgrade between v37.0 to v37.1 will be broken.
> > 
> > 
> > Eeek. I think that is a real shame - this is about kvm_xsave - right? We should look at the length of the serialised data and if it is 4KiB then manually deserialise that part into the field. (This should be a change on main and backported.)
> 
> Yes, the old `xsave` field is 4KiB. I guess we will need to implement a custom `deserilizer` to do it? Do you want to give it try?

Maybe thiss is good (from @roypat):
https://github.com/rust-vmm/kvm-bindings/pull/101/files#diff-ef321b7f850a9b0bfa70204d9e33162d377da6126d1adf522eee5ae1f09df6c7R3974-R3985

**Comment by likebreath** [comment]
@rbradford Okay. I debugged the live-upgrade issue further today and looked into the serialization data. It ended up not an issue from the xsave struct, the `struct kvm_vcpu_events` is the problem. Its size stays the same while a new member `triple_fault` introduced with `reserved` array behind resized [1][2].

I think a custom `deserialize` implementation for  `struct kvm_vcpu_events` will be needed to make sure we can support live-upgrade across different versions of the struct definitions. I will give it a try sometime next week.

On the other hand, I am not sure what's the best way to maintain such custom `deserialize` implementations, particularly if we are planning to have the (de)serde support from kvm-bindings crate directly and avoid forks. /cc @roypat

[1] https://github.com/cloud-hypervisor/kvm-bindings/blob/ch-v0.6.0-tdx/src/x86/bindings.rs#L3192
[2] https://github.com/cloud-hypervisor/kvm-bindings/blob/ch-v0.7.0/src/x86_64/bindings.rs#L3468-L3469

**Comment by rbradford** [comment]
@likebreath I think @roypat added various manual serde serializers/deserializers from our version into the version that has been proposed for kvm-bindings. Seem reasonable to me add more.

I'm also conscious that you are probably eager to get v37.x out - for that case we can continue to use the fork, with a new branch if necessary.

**Comment by roypat** [comment]
> On the other hand, I am not sure what's the best way to maintain such custom deserialize implementations, particularly if we are planning to have the (de)serde support from kvm-bindings crate directly and avoid forks. /cc @roypat

> @likebreath I think @roypat added various manual serde serializers/deserializers from our version into the version that has been proposed for kvm-bindings. Seem reasonable to me add more.

Ah, yeah, I think we could handle this also in kvm-bindings, although this one is slightly more complex because part of the reserved data got "rededicated", so for these cases, kvm-bindings would forever be stuck to deserialize as a `[u8; 27]` and then manually parse it into fields with meaning (e.g. the triple fault structure). I am a bit concerns about the long-term maintainability of this, as the code will grow more and more complex every time more parts of the `reserved` field are assigned structured meaning. 

One long term option (although definitely not backwards compatible with the current implementation) would be to just serialize all kvm-bindings structures as "byte array + len". They're all `repr(C)`, so it would be sound, and the backwards compatibility of Linux's ABI would guarantee us that migrating the same serialized data across bindings generated from different kernel versions would not break:
- If inside some struct the kernel changes `reserved` to actually have some meaning, this is completely transparent to a byte-dump of the structure
- If the kernel _adds_ some fields to the end of a structure, we can detect by comparing the serialized length with `size_of::<T>()`, and appending zeros 
- If we live-downgrade and to a kvm-bindings version where a field does not yet exist, we can truncate the extra bytes (although this probably would break the guest).

If I'm reading your README correctly, you do not support live update across major versions, so would this be a viable long-term solution for CloudHypervisor?

> I'm also conscious that you are probably eager to get v37.x out - for that case we can continue to use the fork, with a new branch if necessary.

I think for your 37.x releases, staying with the fork makes sense. That way we don't have to rush any decision on how to solve the problem upstream :)

**Comment by likebreath** [comment]
> > On the other hand, I am not sure what's the best way to maintain such custom deserialize implementations, particularly if we are planning to have the (de)serde support from kvm-bindings crate directly and avoid forks. /cc @roypat
> 
> > @likebreath I think @roypat added various manual serde serializers/deserializers from our version into the version that has been proposed for kvm-bindings. Seem reasonable to me add more.
> 
> Ah, yeah, I think we could handle this also in kvm-bindings, although this one is slightly more complex because part of the reserved data got "rededicated", so for these cases, kvm-bindings would forever be stuck to deserialize as a `[u8; 27]` and then manually parse it into fields with meaning (e.g. the triple fault structure). I am a bit concerns about the long-term maintainability of this, as the code will grow more and more complex every time more parts of the `reserved` field are assigned structured meaning.
> 
> One long term option (although definitely not backwards compatible with the current implementation) would be to just serialize all kvm-bindings structures as "byte array + len". They're all `repr(C)`, so it would be sound, and the backwards compatibility of Linux's ABI would guarantee us that migrating the same serialized data across bindings generated from different kernel versions would not break:
> 
> * If inside some struct the kernel changes `reserved` to actually have some meaning, this is completely transparent to a byte-dump of the structure
> * If the kernel _adds_ some fields to the end of a structure, we can detect by comparing the serialized length with `size_of::<T>()`, and appending zeros
> * If we live-downgrade and to a kvm-bindings version where a field does not yet exist, we can truncate the extra bytes (although this probably would break the guest).
> 
> If I'm reading your README correctly, you do not support live update across major versions, so would this be a viable long-term solution for CloudHypervisor?
> 

I thought about this idea earlier too: treating all kvm structs as byte arrays, but I didn't think through if this is actually safe or will miss any corner cases. Also, I was not sure if it would make debug potential live-upgrade issues (much) harder. Let's move the discussion to upstream.

> > I'm also conscious that you are probably eager to get v37.x out - for that case we can continue to use the fork, with a new branch if necessary.
> 
> I think for your 37.x releases, staying with the fork makes sense. That way we don't have to rush any decision on how to solve the problem upstream :)

Sounds good. I will keep using a fork for our point releases.

**Comment by likebreath** [comment]
I got distracted from my other duties at work, plus the deadlock issue (#6293) made it a somewhat more complicated. So it took longer than I wanted to it be. :<

Now the live-upgrade should work and live upgrade tests are based on v36.0.

**Review by rbradford — APPROVED** [review]
rslgtm

**Pull request merged**
