### PR TITLE
virtio-devices: vsock: Support single descriptor

### LINKED ISSUE #5691: virtio-vsock doesn't work with v6.3+ guest
I noticed that the Virtio-VSOCK feature stops working if a v6.3+ guest kernel is booted with the v33.0 CH.

This is due to the kernel commit [71dc9ec9ac7d](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=71dc9ec9ac7d3eee785cdc986c3daeb821381e20) ("virtio/vsock: replace virtio_vsock_pkt with sk_buff"), and CH's virtio-vsock backend crate has none support for parsing the new struct sk_buff. In that case, the endless WARN log "WARN --- <vsock> virtio-devices/src/vsock/device.rs:146 -- vsock: RX queue error: BufDescMissing" is easily triggered with documented steps in the [docs/vsock.md](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/vsock.md). 

I'd like to know your thoughts on addressing this bug, an important issue here is how to get the CH backend to maintain compatibility in parsing different formats for guests with unspecified kernel versions.

_Originally posted by @lkml-likexu in https://github.com/cloud-hypervisor/cloud-hypervisor/issues/3822#issuecomment-1683300234_

### PR DESCRIPTION
**Pull request by rbradford**
Since kernel v6.3 the vsock packet is not split over two descriptors
and is instead included in a single one.

This change is based on the discovery and fix identified by Stefano
Garzarella for the vm-virtio vsock implementation and adapted for our
very different codebase.

Fixes: #5691

Signed-off-by: Rob Bradford <rbradford@rivosinc.com>

### CODE REVIEW

**Comment by rbradford** [comment]
@lkml-likexu Please give this a spin!

**Comment by lkml-likexu** [comment]
@rbradford The vsock issue has been fixed, both for v6.2 and v6.3+ guest kernel. Verified based on dbe67fca. Thanks!

**Comment by rbradford** [comment]
@likebreath Can you PTAL? The reporter has confirmed this fixes the issue.

**Comment by likebreath** [comment]
My working hours this week is kind of strange due to jet-lag. I started the review earlier but didn't finish until today.

According to the original fix in the vm-virtio crate (https://github.com/rust-vmm/vm-virtio/pull/207), there is more work to do to make the virtio-vsock implementation fully respect its virtio spec. I quote the following for future references:

>Starting from Linux 6.2 the virtio-vsock driver can use a single descriptor for both header and data:
https://lore.kernel.org/lkml/20221215043645.3545127-1-bobby.eshleman@bytedance.com/
>
>So with this modification the virtio-vsock device can support header and data on a single descriptor or on two. This is just a Linux implementation detail though, for the spec it could be multiple descriptors as well.
>
>For now let's add only the single descriptor support, since it doesn't involve an API change, but in the future we should change the API and support an array of VolatileSlices as suggested by Laura here: https://github.com/rust-vmm/vm-virtio/issues/204#issuecomment-1332511007

**Review by likebreath — APPROVED** [review]

**Comment by rbradford** [comment]
The spec is unfortunately vague about the number of descriptors for all virtio device types (not just vsock) - we've run into issues with block with the Windows driver assuming different; our approach has to been to adapt to handle what the OS does.

**Pull request merged**
