### PR TITLE
misc: Update reference kernel to 6.1.6

### PR DESCRIPTION
**Pull request by rbradford**
Signed-off-by: Rob Bradford <robert.bradford@intel.com>

### CODE REVIEW

**Review by sboeuf — APPROVED** [review]
Looks good to me but apparently the Aarch64 worker failed on the topology integration tests.

**Comment by rbradford** [comment]
@michael2012z @MrXinWang Do you mind taking a look
```
[2023-01-18T15:53:11.213Z] thread 'common_parallel::test_cpu_topology_262' panicked at 'assertion failed: `(left == right)`
[2023-01-18T15:53:11.213Z]   left: `12`,
[2023-01-18T15:53:11.213Z]  right: `6`', tests/integration.rs:617:9
```

and
```
[2023-01-18T15:53:11.208Z] thread 'common_parallel::test_cpu_topology_142' panicked at 'assertion failed: `(left == right)`
[2023-01-18T15:53:11.208Z]   left: `8`,
[2023-01-18T15:53:11.208Z]  right: `4`', tests/integration.rs:617:9
```

Looks like the "Cores per socket" now equals cores * threads on aarch64.

**Comment by michael2012z** [comment]
@rbradford We will look into this. But now we are all on vacation of the Chinese New Year, cannot resolve this immediately. Can you skip the failing test cases on AArch64 temporarily? I will investigate later.

**Comment by likebreath** [comment]
@michael2012z @MrXinWang Happy the Year of Rabbit!

**Comment by rbradford** [comment]
> @rbradford We will look into this. But now we are all on vacation of the Chinese New Year, cannot resolve this immediately. Can you skip the failing test cases on AArch64 temporarily? I will investigate later.

@michael2012z There is no urgency. Enjoy your time off.

**Comment by michael2012z** [comment]
Had a quick look at the problem. It should be caused by an issue in the device tree (the part of describing the CPU topology).

Will be back with a fix soon.

**Comment by michael2012z** [comment]
@rbradford Could you pick the latest commit on this branch to fix the integration failure? https://github.com/michael2012z/cloud-hypervisor/commits/cpu-topology

The problem was triggered by some improvements on ARM CPU topology:
- https://github.com/torvalds/linux/commit/26a2b73a7b15a51ec1409648c9b43882f66fbacf
- https://github.com/torvalds/linux/commit/dea8c0b40fb500be29f4649cf01202e42a8a54f8

There is detailed explanation about the root cause in the commit message.

**Review by MrXinWang — APPROVED** [review]
The Arm fix looks good to me.

**Pull request merged**
