### PR TITLE
tests: test_memory_overhead: use guest.vm_wait_boot

### PR DESCRIPTION
**Pull request by rmstoi**
See: #5738

### CODE REVIEW

**Comment by rmstoi** [comment]
Could there be a bug in guest.vm_wait_boot accept blocks, wrong IP or port?

**Comment by rmstoi** [comment]
> @rbradford Could there be a bug in guest.vm_wait_boot accept blocks, wrong IP or port?

nevermind, I figured out I hope :) the trick is in .default_net()

**Review by rbradford — APPROVED** [review]

**Comment by rbradford** [comment]
Please rebase.

**Comment by rmstoi** [comment]
> Please rebase.

**Pull request merged**
