### PR TITLE
cargo: Bulk update

### PR DESCRIPTION
**Pull request by sameo**
Includes updates for ssh2, cc, syn, tinyvec, backtrace micro-http and libssh2.

Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>

### CODE REVIEW

**Comment by rbradford** [comment]
@sameo Some of the dependabot updates are for the `Cargo.toml` file too.

**Comment by sameo** [comment]
This regroups all pending dependabot PRs.

**Comment by rbradford** [comment]
@sameo You need to use `cargo upgrade` and `cargo update` to bump both the versions in the `Cargo.toml` file and also in the `Cargo.lock`

**Comment by rbradford** [comment]
> @sameo You need to use `cargo upgrade` and `cargo update` to bump both the versions in the `Cargo.toml` file and also in the `Cargo.lock`

See https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1994/files for an example

**Review by rbradford — APPROVED** [review]

**Review by liuw — APPROVED** [review]

**Pull request merged**
