### PR TITLE
Add serial to the disk config doc

### PR DESCRIPTION
**Pull request by wokalski**

### CODE REVIEW

**Comment by liuw** [comment]
Please add a proper prefix ("vmm: ") to the commit message. You need to sign off on the patch.

**Comment by wokalski** [comment]
done :) sorry, i hadnt read the contributing doc

**Comment by liuw** [comment]
> done :) sorry, i hadnt read the contributing doc

No worries.

The sign off line should be like "Signed-off-by: Your Name <EMAIL>". The DCO check failed.

**Comment by rbradford** [comment]
`git commit --amend -s` is the best way to get the correct S-o-B

**Comment by wokalski** [comment]
> git commit --amend -s

TIL, thanks

**Review by rbradford — APPROVED** [review]

**Pull request merged**
