### PR TITLE
build: add gitlint commit message linter

### PR DESCRIPTION
**Pull request by rmstoi**
Implement commit message check workflow using gitlint

Fixes: #5840

### CODE REVIEW

**Comment by likebreath** [comment]
The added workflow is not working: https://github.com/cloud-hypervisor/cloud-hypervisor/actions/runs/6814975913.

Marking this PR as a draft and add WIP prefix to stop running the CI for now.  Please change if needed. Thanks.

FWIW, GH workflow can be validated via personal fork.

**Comment by rbradford** [comment]
I don't want DCO in there since I want DCO to be a required check but the git commit message check only a soft check

**Comment by rmstoi** [comment]
> I don't want DCO in there since I want DCO to be a required check but the git commit message check only a soft check

ok

**Comment by rbradford** [comment]
Any reason not to use this existing action - https://github.com/marketplace/actions/gitlint-action ?

**Comment by rmstoi** [comment]
> Any reason not to use this existing action - https://github.com/marketplace/actions/gitlint-action ?

I tried [GitLint Action](https://github.com/marketplace/actions/gitlint-action), [gitlinter](https://github.com/marketplace/actions/gitlinter) and [commit-message-checker-for-pull-request](https://github.com/marketplace/actions/commit-message-checker-for-pull-request)

[Gitlint](https://github.com/jorisroovers/gitlint) seems to be superior because it is easily configurable, has a commit message hook and user-defined rules, which I used to implement a rule to check that the commit title starts with a valid component name. I also added config to verify that a commit complies with the 50/72 formatting rule.

**Review by rbradford — APPROVED** [review]

**Pull request merged**
