### PR TITLE
Remove "acpi" feature gate

### PR DESCRIPTION
**Pull request by rbradford**
Making this feature optional makes the code complex for very little gain as we only officially support using binaries build with acpi compiled in.

### CODE REVIEW

**Review by sboeuf — APPROVED** [review]
:+1:

**Comment by rbradford** [comment]
@MrXinWang @michael2012z Apologies my request for your review didn't seem to go through. I wanted to check with you jsut in case there was a specific use-case for FDT only builds. (I know that ACPI is not used in the direct kernel boot path on aarch64.)

**Comment by MrXinWang** [comment]
Hi @rbradford, no worries, yesterday I took a look at this PR (quietly though), and personally I am ok with the change.

Also I did a runtime test of the legacy devices of FDT boot and it seems that they are all functional with the change, so no problem so far. Thanks for taking care of removing the acpi feature gate!

**Comment by rbradford** [comment]
Cool, thanks @MrXinWang. In case it was ambiguous the goal was to improve the readability & maintainability of the code.

**Pull request merged**
