### PR TITLE
doc: cloud-hypervisor only supports stream vsock

### PR DESCRIPTION
**Pull request by bouk**

### CODE REVIEW

**Review by rbradford — APPROVED** [review]
Thanks!

**Comment by rbradford** [comment]
@bouk As the CI will tell you - your commit message format is not correct - please review the exist commits to the same/similar files to understand what that format should be.

**Comment by bouk** [comment]
fixed!

**Comment by likebreath** [comment]
Merging the PR now, as it is only document changes.

**Pull request merged**
