### PR TITLE
vmm: config: Close FDs for TAP devices that are provided to VM

### PR DESCRIPTION
**Pull request by rbradford**
These are owned by the config (and are duplicated before being used to
create the `Tap` for the virtio-net device.)

Fixes: #5197

Signed-off-by: Rob Bradford <robert.bradford@intel.com>

### CODE REVIEW

**Comment by rbradford** [comment]
@zhuangel I tested this PR by booting and rebooting with an attached FD from a macvtap setup. I also added extra debugging locally to check that the fd was being closed. Can you try this PR with the issue you were seeing?

**Comment by zhuangel** [comment]
I run my testcase [https://github.com/cloud-hypervisor/cloud-hypervisor/issues/5197](url) in the issue, then boot the VM encounters fail.

```shell
HTTP/1.1 500
Server: Cloud Hypervisor API
Connection: keep-alive
Content-Type: application/json
Content-Length: 163

ApiError(VmBoot(DeviceManager(CreateVirtioNet(TapError(IoctlError(2147767506, Os { code: 25, kind: Uncategorized, message: "Inappropriate ioctl for device" }))))))[root@TENCENT64 snapshot]#
```

```shell
the FD has been closed before boot VM from log file.

...
cloud-hypervisor: 10.748140s: <vmm> INFO:vmm/src/config.rs:1146 -- drop vmconfig close 21
cloud-hypervisor: 10.748435s: <vmm> INFO:vmm/src/config.rs:1153 -- Some("start_thread"): None
cloud-hypervisor: 10.749073s: <vmm> INFO:vmm/src/config.rs:1153 -- Some("__GI___clone"): None
cloud-hypervisor: 10.749113s: <vmm> INFO:vmm/src/config.rs:1166 -- drop netconfig
cloud-hypervisor: 10.749146s: <vmm> INFO:vmm/src/config.rs:1173 -- Some("start_thread"): None
cloud-hypervisor: 10.749181s: <vmm> INFO:vmm/src/config.rs:1173 -- Some("__GI___clone"): None
cloud-hypervisor: 10.749220s: <vmm> INFO:vmm/src/config.rs:1166 -- drop netconfig
cloud-hypervisor: 10.749256s: <vmm> INFO:vmm/src/config.rs:1173 -- Some("start_thread"): None
cloud-hypervisor: 10.749290s: <vmm> INFO:vmm/src/config.rs:1173 -- Some("__GI___clone"): None
cloud-hypervisor: 40.658447s: <vmm> INFO:vmm/src/lib.rs:1786 -- API request event: VmBoot(Sender { .. })
...
```

**Comment by rbradford** [comment]
Okay, this looks like a problem with the HTTP API (I tested with the CLI) please use gdb and set a breakpoint in the drop  function to show where it is being called from.

**Comment by rbradford** [comment]
@zhuangel I was able to identify the extra drop came from the validation logic. I was able to resolve that by manually implementing `Clone` on `NetConfig`. This meant the hotplug then worked.

**Comment by zhuangel** [comment]
> Okay, this looks like a problem with the HTTP API (I tested with the CLI) please use gdb and set a breakpoint in the drop function to show where it is being called from.

I think you can't donate FD via CLI command (either curl nor ch-remote), my test case set FD in cmsg of api socket (unix domain socket), then send it to VMM process.

And this is the GDB information where the donated FD is closed.

```shell
Thread 2 "vmm" hit Breakpoint 1, 0x00007f574864da40 in close () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007f574864da40 in close () from /lib64/libpthread.so.0
#1  0x000055ca864d37c7 in vmm::config::<impl core::ops::drop::Drop for vmm::vm_config::VmConfig>::drop (self=0x7f5748069948)
    at vmm/src/config.rs:1145
#2  0x000055ca864b8577 in core::ptr::drop_in_place<vmm::vm_config::VmConfig> ()
    at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/ptr/mod.rs:490
#3  0x000055ca8633e23e in vmm::Vmm::vm_add_net (self=0x7f5748070a80, net_cfg=...) at vmm/src/lib.rs:1054
#4  0x000055ca8634ae47 in vmm::Vmm::control_loop (self=0x7f5748070a80, api_receiver=...) at vmm/src/lib.rs:1956
#5  0x000055ca863ff717 in vmm::start_vmm_thread::{{closure}} () at vmm/src/lib.rs:338
#6  0x000055ca867df38e in std::sys_common::backtrace::__rust_begin_short_backtrace (f=...)
    at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:121
#7  0x000055ca865d8b7d in std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}} ()
    at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/thread/mod.rs:551
#8  0x000055ca867590ec in <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once (
    self=..., _args=()) at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panic/unwind_safe.rs:271
#9  0x000055ca8657bba0 in std::panicking::try::do_call (data=0x7f57480717e8 "\004\000")
    at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:483
#10 0x000055ca8657ca5b in __rust_try ()
#11 0x000055ca8657ae2c in std::panicking::try (f=...)
    at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:447
#12 0x000055ca8631c79d in std::panic::catch_unwind (f=...)
    at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panic.rs:137
#13 0x000055ca865d6b90 in std::thread::Builder::spawn_unchecked_::{{closure}} ()
    at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/thread/mod.rs:550
#14 0x000055ca864a808f in core::ops::function::FnOnce::call_once{{vtable-shim}} ()
    at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/ops/function.rs:251
#15 0x000055ca86d951c3 in <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once ()
    at library/alloc/src/boxed.rs:1987
#16 <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at library/alloc/src/boxed.rs:1987
#17 std::sys::unix::thread::Thread::new::thread_start () at library/std/src/sys/unix/thread.rs:108
--Type <RET> for more, q to quit, c to continue without paging--
#18 0x00007f574864417a in start_thread () from /lib64/libpthread.so.0
#19 0x00007f574816fdf3 in clone () from /lib64/libc.so.6
```

```shell
"net":[{"tap":null,"ip":"192.168.249.1","mask":"255.255.255.0","mac":"2e:e2:46:f9:5b:32","host_mac":null,"mtu":null,"iommu":false,"num_queues":2,"queue_size":256,"vhost_user":false,"vhost_socket":null,"vhost_mode":"Client","id":null,"fds":[21],"rate_limiter_config":null,"pci_segment":0}]
```

**Comment by zhuangel** [comment]
Hi @rbradford, I tested the code with Clone on NetConfig, after delete the VM via API, tun FD is still held by VMM process, you may need implementing `Drop` on `NetConfig`.

**Comment by rbradford** [comment]
> Hi @rbradford, I tested the code with Clone on NetConfig, after delete the VM via API, tun FD is still held by VMM process, you may need implementing `Drop` on `NetConfig`.

There are two commits on this PR. The second has the implementation of `Drop`. Did you just test a single patch? I followed the steps in #5197 and everything worked fine.

**Comment by zhuangel** [comment]
> > Hi @rbradford, I tested the code with Clone on NetConfig, after delete the VM via API, tun FD is still held by VMM process, you may need implementing `Drop` on `NetConfig`.
> 
> There are two commits on this PR. The second has the implementation of `Drop`. Did you just test a single patch? I followed the steps in #5197 and everything worked fine.

After destroy VM, you could find tun FD still referenced by VMM process
```shell
ls -la /proc/<pid of cloud-hypervisr>/fd | grep tun
```

I tested include two changes `Drop` on `VmConfig` and `Clone` on `NetConfig`, and I found tun FD just exists in NetConfig, such as these:

https://github.com/cloud-hypervisor/cloud-hypervisor/blob/f5084f7c65d721e216d1c30780d7e2949de34ef3/vmm/src/lib.rs#L1048

`Drop` on `VmConfig` only close FD that has referenced in `VmConfig` (via `NetConfig`), We still need `Drop` for `NetConfig` to close FD referenced in `NetConfig`.

**Comment by zhuangel** [comment]
@rbradford I tested with your new branch, the issue has been fixed, no tun FD is held by VMM process after delete the VM.

**Review by liuw — APPROVED** [review]

**Pull request merged**
