### PR TITLE
ci: Update guest kernel to v5.8-rc4

### PR DESCRIPTION
**Pull request by sboeuf**
Updating the kernel from 5.6-rc4 to 5.8-rc4 allows us to remove the
dependency on both virtio-vsock and virtio-mem patches as they are now
part of the upstream kernel. We're still carrying virtio-iommu and
virtio-fs patches.

Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
@MrXinWang @michael2012z once we merge this PR, it'd be nice if you could update the aarch64 side :)

**Comment by michael2012z** [comment]
@sboeuf Sure, we will follow up.

**Comment by sboeuf** [comment]
I need to fix both virtio-fs and virtio-iommu which are broken with this new kernel version.

**Comment by sboeuf** [comment]
Unplugging virtio-fs does not work anymore with this new kernel:
```
[  135.347517] general protection fault, probably for non-canonical address 0xa37366424f344963: 0000 [#1] SMP PTI  
[  135.353330] CPU: 0 PID: 21 Comm: kworker/u2:2 Not tainted 5.8.0-rc4+ #317                                                      
[  135.357176] Hardware name: Cloud Hypervisor cloud-hypervisor, BIOS 0                                                           
[  135.360724] Workqueue: kacpi_hotplug acpi_hotplug_work_fn                                                                      
[  135.363578] RIP: 0010:kill_dax+0xd/0x70                                                                                        
[  135.365642] Code: d0 02 00 00 04 c3 0f 1f 80 00 00 00 00 48 8b 87 d0 02 00 00 83 e0 01 c3 0f 1f 44 00 00 48 85 ff 74 60 55 48 89 e5 53 48 89 fb <3e> 80 a7 d0 02 00 00 fe 48 c7 c7 80 b2 07 ae e8 df 69 bd ff 48 c7
[  135.375052] RSP: 0018:ffffb464000b7b10 EFLAGS: 00010286                                                                        
[  135.377791] RAX: ffffffffad3cdcf0 RBX: a37366424f344963 RCX: 0000000000000282                                                  
[  135.380378] RDX: ffff8e6c7976ec40 RSI: ffff8e6c7976ea98 RDI: a37366424f344963                                                  
[  135.382880] RBP: ffffb464000b7b18 R08: ffffb464000b7b78 R09: ffffb464000b7b78                                                  
[  135.384876] R10: ffff8e6c7c1e9e00 R11: 0000000000000001 R12: ffffb464000b7b78                                                  
[  135.386864] R13: ffff8e6c7976ea80 R14: ffff8e6c7976ea80 R15: ffff8e6c79744ab0                                                  
[  135.388623] FS:  0000000000000000(0000) GS:ffff8e6c7ec00000(0000) knlGS:0000000000000000                                       
[  135.390417] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033                                                                  
[  135.391741] CR2: 00007fcf64d08db0 CR3: 000000003c112001 CR4: 00000000003606b0                                                  
[  135.393248] Call Trace:                                                                                                        
[  135.393808]  virtio_fs_cleanup_dax+0x11/0x20                                                                                   
[  135.394666]  devm_action_release+0x10/0x20                                                                                     
[  135.395468]  release_nodes+0x22c/0x270                                                                                         
[  135.396216]  devres_release_all+0x3a/0x50                                                                                      
[  135.397016]  device_release_driver_internal+0xfb/0x1c0                                                                         
[  135.397974]  device_release_driver+0xd/0x10                                                                                    
[  135.398681]  bus_remove_device+0xdc/0x150                                                                                      
[  135.399369]  device_del+0x16f/0x3f0                                                                                            
[  135.399981]  device_unregister+0x16/0x60                                                                                       
[  135.400662]  unregister_virtio_device+0x13/0x30                                                                                
[  135.401446]  virtio_pci_remove+0x28/0x60                                                                                       
[  135.402119]  pci_device_remove+0x39/0xa0                                                                                       
[  135.402778]  device_release_driver_internal+0xeb/0x1c0                                                                         
[  135.403535]  device_release_driver+0xd/0x10                                                                                    
[  135.404182]  pci_stop_bus_device+0x6b/0x90                                                                                     
[  135.404803]  pci_stop_and_remove_bus_device+0xe/0x20                                                                           
[  135.405573]  disable_slot+0x4a/0x90                                                                                            
[  135.406123]  acpiphp_disable_and_eject_slot+0x15/0x80
[  135.406877]  acpiphp_hotplug_notify+0x184/0x280
[  135.407581]  ? free_bridge+0x130/0x130     
[  135.408165]  acpi_device_hotplug+0xdd/0x390
[  135.408734]  acpi_hotplug_work_fn+0x1d/0x30
[  135.409313]  process_one_work+0x192/0x2e0
[  135.409856]  worker_thread+0x4b/0x3b0
[  135.410359]  kthread+0x10a/0x140           
[  135.410823]  ? process_one_work+0x2e0/0x2e0
[  135.411390]  ? __kthread_parkme+0x60/0x60
[  135.411962]  ret_from_fork+0x22/0x30            
[  135.412501] ---[ end trace bbfed4f67497ceb8 ]---
```

**Pull request merged**
