### PR TITLE
Relicense documentation

### PR DESCRIPTION
**Pull request by rbradford**
The Linux Foundation have recommended the use of this license for documentation. Consent is required from existing contributors to relicense. If no consent is received by 2022-01-31 then we will remove the old documentation.

Here is the new license: https://creativecommons.org/licenses/by/4.0/legalcode

### CODE REVIEW

**Review by sameo — APPROVED** [review]

**Comment by rbradford** [comment]
Dear contributors to Cloud Hypervisor Documentation:

@optimistyzy @yangxile @wfly1998 @weltling @russell-islam @alyssais @iggy @jsoref @glitzflitz @deansheather @eminghuliev @ericooper 

I need to you accept the relicensing  of the documentation to the Attribution 4.0 International (CC BY 4.0). Please try and respond as soon as possible (but not later than 2022-01-31.)

**Review by liuw — APPROVED** [review]

**Review by sboeuf — APPROVED** [review]

**Review by deansheather — APPROVED** [review]

**Review by MrXinWang — APPROVED** [review]

**Review by jsoref — APPROVED** [review]

**Review by weltling — APPROVED** [review]

**Review by wfly1998 — APPROVED** [review]

**Review by likebreath — APPROVED** [review]

**Review by iggy — APPROVED** [review]

**Review by michael2012z — APPROVED** [review]

**Comment by optimistyzy** [comment]
> Dear contributors to Cloud Hypervisor Documentation:
> 
> @optimistyzy @yangxile @wfly1998 @weltling @russell-islam @alyssais @iggy @jsoref @glitzflitz @deansheather @eminghuliev @ericooper
> 
> I need to you accept the relicensing of the documentation to the Attribution 4.0 International (CC BY 4.0). Please try and respond as soon as possible (but not later than 2022-01-31.)

Accept.

**Comment by optimistyzy** [comment]
@optimistyzy  approved this pull request

**Review by alyssais — APPROVED** [review]

**Review by yangxile — APPROVED** [review]

**Comment by rbradford** [comment]
Thank you all who have already commented/approved. The outstanding folks who i'd like sign off from are:

 @glitzflitz @eminghuliev @ericooper

**Comment by rbradford** [comment]
Thank you all for helping us move forward with this!

**Pull request merged**
