### PR TITLE
Seccomp for vhost_user_fs

### PR DESCRIPTION
**Pull request by dagrh**
Add seccomp filtering for vhost_user_fs.
This is built on top of Sergio's https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1071

### CODE REVIEW

**Comment by sboeuf** [comment]
@dagrh you need to run `cargo fmt` and make sure `clippy` does not complain to make sure the first stage of CI will pass.

**Comment by dagrh** [comment]
> @dagrh you need to run `cargo fmt` and make sure `clippy` does not complain to make sure the first stage of CI will pass.

Thanks yes, hopefully the version I've just updated it to fixes my transgressions.

**Comment by sboeuf** [comment]
@dagrh thanks! Just waiting for @slp to address the comment I left, but once we merge his PR, we can surely merge this one :)

**Comment by rbradford** [comment]
@slp ping!

**Comment by slp** [comment]
@rbradford Sorry, this week's been crazy busy. Will update my PR next Monday.

**Comment by sboeuf** [comment]
@dagrh could you please rebase this PR now that we merged Sergio's PR? Once rebased and if the CI still passes, let's merge it!

**Comment by dagrh** [comment]
> @dagrh could you please rebase this PR now that we merged Sergio's PR? Once rebased and if the CI still passes, let's merge it!

Done, hopefully.

**Comment by sboeuf** [comment]
Thanks Dave!

**Comment by rbradford** [comment]
This broke the musl build: https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/job/cloud-hypervisor/job/master/3611/

**Comment by sboeuf** [comment]
@rbradford how did this happen? The CI passed after @dagrh rebased the PR.

**Comment by rbradford** [comment]
The musl build only runs on the master branch.

**Comment by sboeuf** [comment]
Oh yes the build is validated on each PR, but the integration tests only run on master :(

**Comment by sboeuf** [comment]
@rbradford just checking, are you sure this is this PR, because right before we merged https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1071 which introduced a bunch of syscall being invoked.

**Comment by rbradford** [comment]
> @rbradford just checking, are you sure this is this PR, because right before we merged https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1071 which introduced a bunch of syscalls being invoked.

That link I gave above only lists this change between the last build (which was fine) and this one.

**Comment by dagrh** [comment]
> > @rbradford just checking, are you sure this is this PR, because right before we merged #1071 which introduced a bunch of syscalls being invoked.
> 
> That link I gave above only lists this change between the last build (which was fine) and this one.

Do we have some notes on how to do a musl build?
If anyone has a build to hand and can try it, they can check their audit log to see which syscall blew up and/or try starting with --seccomp none    to verify the problem goes away.

**Comment by rbradford** [comment]
@dagrh I fixed it in #1186

**Comment by dagrh** [comment]
> @dagrh I fixed it in #1186

Thank you!

**Pull request merged**
