### PR TITLE
vmm: api: Do not delete the API socket on API server creation

### LINKED ISSUE #4026: cloud-hypervisor delete the file api-socket
**Describe the bug**
Run command `cloud-hypervisor --api-socket /tmp/ch.sock`,  then run the command `cloud-hypervisor --api-socket /tmp/ch.sock` again. The second instance deletes the file `/tmp/ch.sock` blindly and we could not connect to the first instance now. 
Is this a bug or does it work as designed?

**To Reproduce**
Run command `cloud-hypervisor --api-socket /tmp/ch.sock` twice.

### PR DESCRIPTION
**Pull request by xyz-li**
The socket will safely deleted on shutdown and so it is not necessary to
delete the API socket when starting the HTTP server.

Fixes: #4026

Signed-off-by: LiHui <andrewli@kubesphere.io>
Signed-off-by: Rob Bradford <robert.bradford@intel.com>

### CODE REVIEW

**Review by rbradford — CHANGES_REQUESTED** [review]
I need some time to analyse if this is the correct approach.

**Comment by xyz-li** [comment]
I have read the code of  `firecracker`. It does not remove the file `api-scok`.

**Comment by sboeuf** [comment]
@rbradford IMO this is a legitimate issue and we shouldn't blindly remove the socket file. My suggestion:
- We don't remove the socket path before to try binding to it
- We add some code to remove the socket path when terminating the VMM process
- In case of Cloud Hypervisor being killed with SIGKILL, we expect the management layer will take care of cleaning up the socket path

**Comment by xyz-li** [comment]
```
    let exit_code = match start_vmm(cmd_arguments) {
        Ok(path) => {
            path.map(|s| std::fs::remove_file(s).ok());
            0
        }
        Err(e) => {
            eprintln!("{}", e);
            1
        }
```
cloud-hypervisor will delete the socket file when exits.

**Comment by rbradford** [comment]
@xyz-li Thank When creating a commit for a new commit it's a generally a good idea to look at the style of the other commits in the repository. I've updated your commit and PR to match those.

**Review by sboeuf — APPROVED** [review]

**Comment by xyz-li** [comment]
> Which we do get: (which certainly could be improved: `Failed to start the VMM thread: Error creation API server's socket Os { code: 98, kind: AddrInUse, message: "Address already in use" }`)

I also think the error output is not friendly. Actually, I think most of the error outputs of cloud-hypervisor are not friendly.
For example, when I want to create two VM in a cloud-hypervisor instance, the output is `ApiError(VmCreate(VmAlreadyCreated))`.

**Review by rbradford — APPROVED** [review]

**Comment by rbradford** [comment]
The tests that do snapshot and restore are failing: (`test_snapshot_restore` and `test_ovs_dpdk`

**Pull request merged**
