### PR TITLE
deps: Move to parking_lot::{Mutex, RwLock}

### LINKED ISSUE #3684: Evaluate using parking_lot
https://lib.rs/crates/parking_lot

> This library provides implementations of Mutex, RwLock, Condvar and Once that are smaller, faster and more flexible than those in the Rust standard library, as well as a ReentrantMutex type which supports recursive locking. It also exposes a low-level API for creating your own efficient synchronization primitives.

### PR DESCRIPTION
**Pull request by sboeuf**
Fixes #3684

Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
Posting the patch to check if the CI runs okay.
Still need to assess the potential gain in performance.

**Comment by sboeuf** [comment]
The PR is passing, but I don't think it's worth moving to `parking_lot` since the `metrics` CI doesn't show any performance improvement.
/cc @rbradford @liuw

**Comment by rbradford** [comment]
@sboeuf You could try removing the metrics filter and see if any of the other metrics change. I think that the boot was good first check as I believe if is the place with the most cross thread interaction and thus potential lock interactions.

**Comment by sboeuf** [comment]
@rbradford the filter didn't filter anything, you can see the full metrics report from the last two Jenkins jobs.

**Comment by rbradford** [comment]
> @rbradford the filter didn't filter anything, you can see the full metrics report from the last two Jenkins jobs.

Ah yes, please open a bug that `--test-filter` didn't work correctly.

**Comment by rbradford** [comment]
> The PR is passing, but I don't think it's worth moving to `parking_lot` since the `metrics` CI doesn't show any performance improvement. The benefit would be to rely on a more appropriate implementation than the standard library as it relies on `futex()` on Linux rather than `pthread_mutex`, hence leading to potential undefined behaviors. /cc @rbradford @liuw

I agree that it makes sense to depend on the std library. It would be good to ensure that the performance results (and lack of an improvement compared to main) are included on the originating issue which can then be closed. Thank you for evaluating this.

**Comment by liuw** [comment]
Thanks for evaluating parking_lot.

Perhaps some very dumb questions: does the metric run use io_uring to access raw disk? How many queues does it use?

The one scenario I can think of that parking_lot may help is accessing QCOW or VHD disks. From I can see there is a mutex that locks the the whole file.

**Comment by sboeuf** [comment]
> Thanks for evaluating parking_lot.

Sure :)

> 
> Perhaps some very dumb questions: does the metric run use io_uring to access raw disk? How many queues does it use?

It uses `io_uring` and performs both single queue and multi queue (2 queues) tests.

> 
> The one scenario I can think of that parking_lot may help is accessing QCOW or VHD disks. From I can see there is a mutex that locks the the whole file.

That *might* help, but the boot also performs a bunch of locking, and we can't see any significant performance improvement with boot time.
I'll try increasing the amount of queues and to use VHDx backing file, see if I can get any performance gain from there.

**Comment by liuw** [comment]
> > Perhaps some very dumb questions: does the metric run use io_uring to access raw disk? How many queues does it use?
> 
> It uses `io_uring` and performs both single queue and multi queue (2 queues) tests.
> 

Hmm... Perhaps it also makes sense to bump the number of queues to a larger number? For example 16 or 32 or to the number of CPUs to create more contention?

**Comment by sboeuf** [comment]
> I'm curious if you'd see any difference if you enable the hardware-lock-elision feature (for x86_64).

IIUC, this could be beneficial for both approaches, right?

**Comment by sboeuf** [comment]
Closing this PR, based on the results found and posted there https://github.com/cloud-hypervisor/cloud-hypervisor/issues/3684.

**Pull request closed without merging**
