### PR TITLE
Failing to finish TPM requests should be considered fatal

### PR DESCRIPTION
**Pull request by liuw**
At first glance there isn't much value in allowing the guest to continue using TPM after that.

### CODE REVIEW

**Review by rbradford — APPROVED** [review]
Looks good to me.

**Comment by praveen-pk** [comment]
The current implementation of TPM doesn't support any critical services like Secure Boot. So, I thought if a TPM request fails, the rest of the VM should continue.
For example, if swtpm process got killed/crashed on the host, TPM requests will not succeed. In such a situation wouldn't it better for guest to continue with any ongoing workloads, save some state and then try and resolve the TPM Issue?

**Comment by liuw** [comment]
> The current implementation of TPM doesn't support any critical services like Secure Boot. So, I thought if a TPM request fails, the rest of the VM should continue. For example, if swtpm process got killed/crashed on the host, TPM requests will not succeed. In such a situation wouldn't it better for guest to continue with any ongoing workloads, save some state and then try and resolve the TPM Issue?

Setting the TPM state to fatal does not kill the VM. A sane guest driver will recognize that and stop using TPM.

The code as-is makes the guest think the request succeeded when it wasn't. Continuing in this state is not correct.

**Review by sboeuf — APPROVED** [review]

**Comment by praveen-pk** [comment]
To test this behavior, I killed the swtpm process after a guest booted successfully. That should cause `deliver_request()` to error out. With this patch, I expected the guest to report an error and continue. 

But, with or without this patch, I see the guest is getting stuck. May be a read on the tpm socket is blocking the guest. So, the guest never gets to this code.

I'd like to see clh exercise this code change before merging it in.

**Comment by praveen-pk** [comment]
any ideas on how we can exercise this code in a test?

**Comment by liuw** [comment]
> To test this behavior, I killed the swtpm process after a guest booted successfully. That should cause `deliver_request()` to error out. With this patch, I expected the guest to report an error and continue.
> 
> But, with or without this patch, I see the guest is getting stuck. May be a read on the tpm socket is blocking the guest. So, the guest never gets to this code.
> 

Right, I think that's blocking the vcpu thread.

Perhaps this can help? https://doc.rust-lang.org/std/os/unix/net/struct.UnixStream.html#method.set_read_timeout

**Comment by praveen-pk** [comment]
cloud-hypervisor is blocking at `recvfrom` at https://github.com/cloud-hypervisor/cloud-hypervisor/blob/938c16f2b287bd2286d4cee500d13b3c558d3956/tpm/src/emulator.rs#L324  I added a timeout to the data socket being used and saw the following:

# run selftest after killing myswtpm without this patch
``` 
testuser@chtestvm:~$ sudo tpm2_selftest
WARNING:esys:src/tss2-esys/api/Esys_SelfTest.c:269:Esys_SelfTest_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_SelfTest.c:95:Esys_SelfTest() Esys Finish ErrorCode (0x00000143)
ERROR: Esys_SelfTest(0x143) - tpm:error(2.0): command code not supported
ERROR: Unable to run tpm2_selftest
```
# run selftest after killing myswtpm with this patch

```
testuser@chtestvm:~$ sudo tpm2_selftest
[   55.075751] tpm tpm0: tpm_transmit: tpm_recv: error -5
ERROR:tcti:src/tss2-tcti/tcti-device.c:486:Tss2_Tcti_Device_Init() Failed to read response header fd 3, got errno 5: Input/output error
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-device.so.0 [   57.187978] tpm tpm0: tpm_transmit: tpm_recv: error -5

ERROR:tcti:src/tss2-tcti/tcti-device.c:486:Tss2_Tcti_Device_Init() Failed to read response header fd 3, got errno 5: Input/output error

ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-device.so.0
WARNING:tcti:src/util/io.c:262:socket_connect() Failed to connect to host 127.0.0.1, port 2321: errno 111: Connection refused
ERROR:tcti:src/tss2-tcti/tcti-swtpm.c:614:Tss2_Tcti_Swtpm_Init() Cannot connect to swtpm TPM socket
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-swtpm.so.0
WARNING:tcti:src/util/io.c:262:socket_connect() Failed to connect to host 127.0.0.1, port 2321: errno 111: Connection refused
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-mssim.so.0
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:254:tctildr_get_default() No standard TCTI could be loaded
ERROR:tcti:src/tss2-tcti/tctildr.c:428:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI
ERROR: Could not load tcti, got: "(null)"
```

This patch is not crashing the guest and also allows tpm to return proper error message. Please go ahead and merge this patch. I will push timeout patch after some clean up.

**Review by praveen-pk — APPROVED** [review]

**Pull request merged**
