### PR TITLE
Dockerfile: Update to build the latest upstream SPDK

### PR DESCRIPTION
**Pull request by likebreath**
The latest SPDK contains live-migration support for the NVMe backend.

Signed-off-by: Bo Chen <chen.bo@intel.com>

### CODE REVIEW

**Comment by MrXinWang** [comment]
Hi @likebreath, sorry but could you please also bump the aarch64 SPDK in here https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/scripts/run_integration_tests_aarch64.sh#L59? Thanks!

**Comment by rbradford** [comment]
As well as bumping the aarch64 version if you increase the date on the dev_cli.sh script your change to the Dockerfile will actually get tested by the CI as the workers will build the container before running the integration tests.

**Comment by likebreath** [comment]
@rbradford @MrXinWang PR updated. PTAL. 

It is good to know that I can update the  Dockerfile and `CTR_IMAGE_VERSION`  in the same PR. (I thought I had to send a separate PR to update the `CTR_IMAGE_VERSION`). This definitely simplifies things as I can also bump the version for aarch64 in the same PR.

**Comment by likebreath** [comment]
Also, I was running the `test_vfio_user` locally with the updated SPDK version (for `x86_64`), and it has been passing for over 3000 iterations. So it should be fairly stable with the SPDK version bump.

**Review by MrXinWang — APPROVED** [review]

**Comment by likebreath** [comment]
Considering the UTC time is already April 5, just updated the container version (date) to `CTR_IMAGE_VERSION="20220405-0"`. Hopefully it would match the actual container tag version that will be built/pushed by GH action after this PR is landed.

**Review by sboeuf — APPROVED** [review]

**Pull request merged**
