### PR TITLE
scripts: Set secure protocol as TLSv1_2 for wget on aarch64 worker

### PR DESCRIPTION
**Pull request by likebreath**
By default, the the secure protocol is set 'auto' for wget which allows
the underline SSL library to choose an appropriate protocol. With some
experiments on the aarch64 worker machine, I found using the 'TLSv1_3'
protocol can cause wget failures with error "SSL handshake failed" while
'TLSv1_2' works fine.

### CODE REVIEW

**Comment by likebreath** [comment]
@michael2012z I am not sure if this is the best way to fix the issue. Please take a look and let me know your thoughts.

For the context, the aarch64 worker started to fail due to this wget error since the end of last week. Here is the latest one with some logs: https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/blue/rest/organizations/jenkins/pipelines/cloud-hypervisor/branches/main/runs/726/nodes/47/log/?start=0

**Comment by michael2012z** [comment]
@likebreath I agree to take this workaround to unblock other PRs. I will look into why this happened.

Not sure if it's related to the container where the integration is running in. On the CI host, the `wget` works well.

**Comment by michael2012z** [comment]
Created an issue to track: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/6006

**Comment by likebreath** [comment]
> @likebreath I agree to take this workaround to unblock other PRs. I will look into why this happened.
> 
> Not sure if it's related to the container where the integration is running in. On the CI host, the `wget` works well.

@michael2012z  Right. I can't reproduce this either on the host machine. I have to use `wget --secure-protocol=TLSv1_3` to reproduce the same error being observed from our CI pipeline, while `--secure-protocol=TLSv1_2` always work from my experiment. This is why I send the PR in this way, but not sure if this would resolve the actual problem. I will run the CI couple of more times, remove the DEBUG commit, and let you decide if you want to merge this PR. Thanks.

**Comment by likebreath** [comment]
Not working. See https://github.com/cloud-hypervisor/cloud-hypervisor/issues/6006#issuecomment-1839975633.

**Pull request closed without merging**
