### PR TITLE
ci: Update the OVMF version the tests rely on

### PR DESCRIPTION
**Pull request by sboeuf**
Bumping the OVMF binary version to reflect the latest set of patches on
top of tianocore/edk2 'master' branch, which can be found on the Cloud
Hypervisor fork on 'ch' branch.

Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

### CODE REVIEW

**Review by rbradford — APPROVED** [review]

**Comment by liuw** [comment]
Does this mean there is no need to carry Cloud Hypervisor specific changes in OVMF?

**Comment by sboeuf** [comment]
>Does this mean there is no need to carry Cloud Hypervisor specific changes in OVMF?

No it means I've updated the patchset on top of upstream and I'm sending the patches for review. Only once the patches will be accepted upstream, we won't need any specific change.

**Comment by sboeuf** [comment]
@rbradford the size and load address look just fine and as expected from the second Jenkins run with the added logs.
I really think the issue came from a buggy KVM version used from the Azure VM. If you look at the third run, things are now resolved and there's only one legitimate issue related to snapshot/restore:
```
cloud-hypervisor: 28.391173ms: <vmm> INFO:vmm/src/memory_manager.rs:1444 -- Creating userspace mapping: 0 -> 7fce84000000 c0000000, slot 3
cloud-hypervisor: 29.798457ms: <vmm> INFO:vmm/src/memory_manager.rs:1478 -- Created userspace mapping: 0 -> 7fce84000000 c0000000
cloud-hypervisor: 29.815056ms: <vmm> INFO:vmm/src/memory_manager.rs:1444 -- Creating userspace mapping: 100000000 -> 7fce44000000 40000000, slot 4
cloud-hypervisor: 30.128153ms: <vmm> INFO:vmm/src/memory_manager.rs:1478 -- Created userspace mapping: 100000000 -> 7fce44000000 40000000
cloud-hypervisor: 30.143653ms: <vmm> INFO:vmm/src/memory_manager.rs:1444 -- Creating userspace mapping: ffc00000 -> 7fcf52426000 400000, slot 5
cloud-hypervisor: 30.167952ms: <vmm> INFO:vmm/src/memory_manager.rs:1478 -- Created userspace mapping: ffc00000 -> 7fcf52426000 400000
Error restoring VM: VmRestore(MemoryManager(MemoryRangeAllocation))
```

**Comment by sboeuf** [comment]
@rbradford this PR should now contain the right fix. The problem was that the entire 32-bit memory hole (from 3GiB up to 4GiB) was reserved through the `ram_allocator`, causing a conflict with the last 4MiB at the end of the range that we need for the firmware.
Feel free to propose a better fix if you can think of something better :)

**Comment by rbradford** [comment]
@sboeuf What about this as a solution: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/3403 ?

**Comment by sboeuf** [comment]
@rbradford I've just pushed with your patch https://github.com/cloud-hypervisor/cloud-hypervisor/pull/3405, let's see if that makes any difference.

**Comment by sboeuf** [comment]
@rbradford funny issue! The problem comes from a conflict with the 3 pages region at TSS address. And the funny part is that it doesn't happen on every build because depending on the underlying hardware, KVM actually sets it or not. But when it's set/needed well we end up with a conflict.
There's a second issue, that's when KVM create the vCPU, again depending on the processor it needs the identity map address to be set. A single page located at 0xfffbc000. For this one, we must implement KVM_SET_IDENTITY_MAP_ADDR if we want to be able to fix it.

**Comment by rbradford** [comment]
Okay, lets use `KVM_SET_IDENTITY_MAP_ADDR` and `KVM_CAP_SET_TSS_ADDR` in the space we have between the end of the 32-bit device area and the firmware area?

**Comment by sboeuf** [comment]
Relies on #3411, therefore we need to wait for #3411 to be merged before we can move forward with this PR.

**Comment by sboeuf** [comment]
#3411 has been merged, this PR is ready now.

**Review by rbradford — APPROVED** [review]

**Pull request merged**
