### PR TITLE
RFC: Improve migration (restore path)

### PR DESCRIPTION
**Pull request by sboeuf**

### CODE REVIEW

**Review by likebreath — COMMENTED** [review]
Looking good to me. It turned out to be much less changes than I expected as you made the snapshot available from the `Vm` struct that is directly accessible to all `virtio-device` constructors.

**Comment by likebreath** [comment]
Also, I think you will need to swap the order of restoring `DeviceManager` and  `CpuManager` to meet the recruitment of migration on aarch64 (e.g. VGIC has to be created after VCPUs creation). I did a quick experiment locally and that works fine at least for x86_64.

**Comment by sboeuf** [comment]
> Looking good to me. It turned out to be much less changes than I expected as you made the snapshot available from the `Vm` struct that is directly accessible to all `virtio-device` constructors.

Oh yeah providing the Snapshot to each device isn't the big part of the change. The big change is that I'll have to apply this design for each Migratable object, and that's a lot :)

**Comment by sboeuf** [comment]
> Also, I think you will need to swap the order of restoring `DeviceManager` and `CpuManager` to meet the recruitment of migration on aarch64 (e.g. VGIC has to be created after VCPUs creation). I did a quick experiment locally and that works fine at least for x86_64.

Ah you might be right, I'll have to check once I'm there.

**Pull request closed without merging**
