### PR TITLE
tests: Add integration test for vfio-user with SPDK NVMe

### PR DESCRIPTION
**Pull request by likebreath**
This PR depends on #3255. 

Fixes: #3098

Signed-off-by: Bo Chen <chen.bo@intel.com>

### CODE REVIEW

**Comment by likebreath** [comment]
> The test looks good, but a better way of checking if the NVMe device is functional is by booting from it. So I'd suggest you add another test for it. Basically you would provide the guest image through the SPDK backend, and you would change the kernel boot command line to use `root=/dev/nvme0p1`.

I just tested it locally, and booting from spdk-nvme works well. Adding this test is fairly straight-forward, but the only tricky part is that I will need to verify whether I can use the `nvmf_tgt` to present two NVMe devices at the same time (assuming we want to run both tests in parallel mode).

**Comment by likebreath** [comment]
> Did a quick test and the build passed on arm64 machine with command `./scripts/dev_cli.sh build-container`.

@MrXinWang By following what's done from the GH action, I am able to reproduce the error on my x86_64 machine. It was using docker cross-platform building feature: `docker buildx build --platform=linux/arm64 ...`. 

The error I got was the same as what the GH action complained. As `docker buildx` is using the preinstalled qemu-static, it looks like something that is missing from QEMU side (given your `docker build` on beremetal works)? What's your thoughts and advises? Thank you.

```
config/arm/meson.build:445:16: ERROR: Problem encountered: Error when getting Arm Implementer ID and part number.
```

**Comment by MrXinWang** [comment]
> The error I got was the same as what the GH action complained. As `docker buildx` is using the preinstalled qemu-static, it looks like something that is missing from QEMU side (given your `docker build` on beremetal works)? What's your thoughts and advises? Thank you.
> 
> ```
> config/arm/meson.build:445:16: ERROR: Problem encountered: Error when getting Arm Implementer ID and part number.
> ```

By taking a very quick look at the DPDK (I assume SPDK is similar) install/config process here (http://code.dpdk.org/dpdk/latest/source/config/arm/meson.build#L445), I think maybe the problem is related to the platform config and we need to config the platform to generic here (https://github.com/cloud-hypervisor/cloud-hypervisor/commit/690bdc3448c04c607a7d0b184dbac0edd261506a#diff-ff2f4888711e4b598b54c199067544601d022da8d5713e9cf72da0e7bd8c8673L120)? But I just woke up and didn't try on real machine so this is just my wild guess. Let me try and get back to you :)))

**Comment by likebreath** [comment]
> Looks like the DPDK build is triggered in the middle of the SPDK build, so I also wonder if we can directly configure the DPDK without hacking the makefile...

@MrXinWang Thanks a lot for digging into the issue. If we still can't find solution to resolve the `docker buildx` problem, I think we can pre-install SPDK for x86 docker image only while keeping the SPDK build as a part of the CI for aarch64 for now. I will let you make the call, from where I can send an updated PR for #3235 and land this one. Appreciate your time and help.

**Comment by michael2012z** [comment]
Hi, @likebreath @MrXinWang Totally agree with you. Please continue, and let's see how vfio_user is working on AArch64.

**Comment by likebreath** [comment]
@MrXinWang @michael2012z Would you please help look at the SPDK building failure on the bare-metal CI machine for aarch64? It was complaining `"ERROR: Could not detect Ninja v1.8.2 or newer"`, while from the CI log above I did see "`Successfully installed ninja-1.10.2.2`". One full log is [here](https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/blue/rest/organizations/jenkins/pipelines/cloud-hypervisor/branches/PR-3236/runs/6/nodes/111/steps/120/log/). Thank you.

**Comment by MrXinWang** [comment]
@likebreath Done and thanks for the effort!

**Comment by optimistyzy** [comment]
> > @MrXinWang Thanks a lot for digging into the issue. I wonder any luck with setting the machine/platform as generic?
> 
> Hi @likebreath not really....I will spend some more time today if I have time. What I found is that the `configure` of SPDK does not have such platform configuration option. Also I tried to build with the `SKIP_DPDK_BUILD=1` and the build failed because of some missing header files:
> 
> ```
> In file included from env.c:39:
> env_internal.h:41:10: fatal error: rte_config.h: No such file or directory
>    41 | #include <rte_config.h>
>       |          ^~~~~~~~~~~~~~
> compilation terminated.
> ```
> 
> Looks like the DPDK build is triggered in the middle of the SPDK build, so I also wonder if we can directly configure the DPDK without hacking the makefile...

You can compile DPDK externally, then when you build SPDK, you can link the external DPDK library. Otherwise, SPDK will download dpdk submodule, built it and use this DPDK. Usually, the dpdk submodule has some own fixes.

**Comment by likebreath** [comment]
Close the PR for now while debugging the issue of SPDK-NVMe that can cause systemd crashing in the guest while booting/rebooting.

**Pull request closed without merging**
