### PR TITLE
vmm: api: Make NetConfig structure more OpenAPI friendly

### PR DESCRIPTION
**Pull request by sboeuf**
In order to keep things consistent between the CLI and the HTTP API, this pull request submit some changes to the NetConfig structure. It will be possible for a consumer of the API to have the same level of functionality as if it was using the CLI.

### CODE REVIEW

**Comment by sboeuf** [comment]
Supersedes #480

**Comment by rbradford** [comment]
@sboeuf I think you need to update the json used by the integration tests....

**Comment by sboeuf** [comment]
@rbradford I think the problem is because now we need a default value for `tap`.

**Comment by sboeuf** [comment]
This is definitely more complex than expected, the combination of OpenAPI and serde makes things hard to anticipate. I'll come up with another PR once I get things sorted out.

**Pull request closed without merging**
