### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by jsoref**
This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).

The misspellings have been reported at https://github.com/jsoref/cloud-hypervisor/commit/971223e916140daf85fd25e7318c23fa388e3d2e#comments

The action reports that the changes in this PR would make it happy: https://github.com/jsoref/cloud-hypervisor/commit/1f5de12c7ea000f21140a6961c7be0c08f7eed23

Note: this PR does not include the action. If you're interested in running a spell check on every PR and push, that can be offered separately.

### CODE REVIEW

**Comment by sboeuf** [comment]
@jsoref could you please squash all the commits into a single one?

Also, please go ahead and submit a PR to enable the spell check through github actions.

**Review by sboeuf — COMMENTED** [review]
Since this is now a single commit (thanks for fixing that), could you be a bit more verbose in the commit message title and commit message body to explain what this commit is doing instead of listing all the words it actually fixed (since we can see that from the code directly).

**Comment by jsoref** [comment]
Hmm.. I guess. I'm not very creative about the commit messages. (Partially because I do a lot of them.)

Do you have a specific suggestion?

```
chore: Fix various misspelled words
```

I can identify the tool I used (which makes a bit of sense given that you've asked for a PR for that as well) / the way I picked replacements (most of these were suggested by **Google Sheets**' spell checker, although some may have been suggested by **Google Chrome**'s url bar suggestion, and occasionally I manually pick the correct word).

**Comment by sboeuf** [comment]
>Hmm.. I guess. I'm not very creative about the commit messages. (Partially because I do a lot of them.)
Do you have a specific suggestion?

`ch: Fix various misspelled words` would be great (I'm not sure what `chore` meant, that's why I recommended `ch` to detail this commit refers to the entire project).

>I can identify the tool I used (which makes a bit of sense given that you've asked for a PR for that as well) / the way I picked replacements (most of these were suggested by Google Sheets' spell checker, although some may have been suggested by Google Chrome's url bar suggestion, and occasionally I manually pick the correct word).

You can give this amount of details, this is great, but the most important is to start with an explanation about what the commit is doing and what problem it is trying to solve.

**Comment by jsoref** [comment]
I generally don't include the `chore:` prefix, but some projects w/ semantic commit rules seem to push it, which is why I included it when I squashed the commits. I'm happy to omit that as I'm not attached to it.

I used to have a longer preamble in my PRs explaining that misspellings make it harder to search for things, harder to understand things, increase the risk of ambiguity, etc., but of late, I've mostly dropped it. (I think I tend to use the longer form when I'm making a really large PR to a project and it has a mix of API changes / comments / docs / functions / locals. This PR is almost entirely comments w/ perhaps a couple of functions.)

**Review by sboeuf — APPROVED** [review]
LGTM!
@rbradford PTAL

**Review by rbradford — APPROVED** [review]
rslgtm

**Pull request merged**
