### PR TITLE
README: Add slack channel for community activity

### PR DESCRIPTION
**Pull request by ailun258**
Fixes: #5264 
Signed-off-by: ailin.yang@intel.com
community users can get community activities easily in main portal of project.

### CODE REVIEW

**Comment by ailun258** [comment]
hi @rbradford @likebreath closed #5265 #and submit new one according to your comments

**Comment by liuw** [comment]
@ailun258 Please put a Signed-off-by tag in the commit message. See here https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5269/checks?check_run_id=11904839375.

**Review by likebreath — COMMENTED** [review]
@ailun258 I tried to fix your commit on your behalf but looks like the commit was done with a different email (via GitHub UI). See the following error:
```
sign-off not found for commit author: ailin_yang 99698180+ailun258@users.noreply.github.com; found: ['ailin.yang@intel.com']
```

To fix it, you will need to checkout your branch locally, commit with your Intel email, and force-push to your remote branch. Also, you won't need to create a new PR and can reuse this one. Also, a issue is not required as long as the PR is self-explainable. 

Any help you need, just let me know.

**Comment by ailun258** [comment]
it’s a small patch, I submitted it through GitHub Ui directly. looks like UI doesn’t have  auto sign capability.
I will checkout locally and submit.

thanks
Ailin

**Pull request closed without merging**
