### PR TITLE
MSVH VFIO based passthrough support

### PR DESCRIPTION
**Pull request by liuw**
This patch set implements VFIO based passthrough for MSHV.

This won't work until https://github.com/rust-vmm/mshv/pull/11 and https://github.com/rust-vmm/vfio-ioctls/pull/22 are merged.

It is however in a state that can get some feedback from the community.

### CODE REVIEW

**Comment by liuw** [comment]
@sboeuf @rbradford the CI failures are expected. I will fix them after the prerequisites are merged. In the meantime if I can get some feedback on patch 2 and 3 that'll be great.

**Comment by rbradford** [comment]
> @sboeuf @rbradford the CI failures are expected. I will fix them after the prerequisites are merged. In the meantime if I can get some feedback on patch 2 and 3 that'll be great.

I think it looks good @liuw

**Comment by liuw** [comment]
Prerequisite patches to mshv and vfio-ioctls have been merged. This PR is ready for review.

**Review by rbradford — APPROVED** [review]

**Comment by liuw** [comment]
@rbradford Perhaps something to mention for the v18 release?

**Pull request merged**
