### PR TITLE
virtio-device: fix some misspelled words in comment

### PR DESCRIPTION
**Pull request by up2wing**
Fix some trivial spelling problem.
No functional change.

Signed-off-by: Yi Wang <wang.yi59@zte.com.cn>

### CODE REVIEW

**Review by sboeuf — APPROVED** [review]

**Comment by sboeuf** [comment]
It needs some rebasing.

**Comment by up2wing** [comment]
> It needs some rebasing.

thanks for the advise. @sboeuf 
I resolve the conflicts and the patch should merge now.
Sorry for the inconvenience :(

**Comment by rbradford** [comment]
There is a merge commit in this PR

**Comment by up2wing** [comment]
> There is a merge commit in this PR

ok. I will rebase my branch and open a new PR.
Thanks. @rbradford

**Pull request closed without merging**
