### PR TITLE
Emulate MOVZX instruction

### PR DESCRIPTION
**Pull request by sameo**

### CODE REVIEW

**Review by sboeuf — APPROVED** [review]
Neat!

**Comment by sameo** [comment]
@liuw could you PTAL and give it a try?

**Comment by liuw** [comment]
> 
> 
> @liuw could you PTAL and give it a try?

My test box is currently occupied by my kernel work. @vineethrp can you give it a try if your setup is still available?

**Comment by vineethrp** [comment]
I confirm that linux guest now boots on mshv with this PR. Thanks @sameo  for the quick fix :-)

**Comment by sameo** [comment]
Thanks for the feedback @vineethrp and @liuw! Merging now.

**Pull request merged**
