### PR TITLE
Share common code between different virtio devices

### PR DESCRIPTION
**Pull request by rbradford**
Initially only block is covered but I will add more to this PR if the CI goes green.

### CODE REVIEW

**Review by sboeuf — APPROVED** [review]
Really good PR so far. Let me know if you want to add more things or if you'd like me to merge it.

**Comment by rbradford** [comment]
@sboeuf thanks for your feedback. My plan is to try and port some more first to check that this is going along the right lines.

**Comment by rbradford** [comment]
@sboeuf I've done everything I wanted to do on this PR for today...PTAL

**Review by sboeuf — APPROVED** [review]
@rbradford still looks very good to me :)

**Pull request merged**
