### PR TITLE
Fix beta clippy issues

### PR DESCRIPTION
**Pull request by rbradford**

### CODE REVIEW

**Review by MrXinWang — APPROVED** [review]
AArch64 part looks good. Thanks for the change!

**Comment by rbradford** [comment]
> AArch64 part looks good. Thanks for the change!

Okay, cool. I wasn't sure if the PL011 and PL031 devices are thoroughly tested by the integration tests.

**Comment by MrXinWang** [comment]
> Okay, cool. I wasn't sure if the PL011 and PL031 devices are thoroughly tested by the integration tests.

Let me do a quick manual test then, but it should be good, as for the PL031 RTC, if the RTC functionality is broken, the UEFI/ACPI test case will definitely fail. The PL011 UART should be the same I expect.

**Review by liuw — APPROVED** [review]

**Comment by MrXinWang** [comment]
Hi @rbradford, I did not see any functional regression (both device tree and ACPI) from my manual tests of PL011 and PL031. So I think the change is safe. Thanks!

**Pull request merged**
