### PR TITLE
build: Add quality (clippy & rustfmt) using beta toolchain

### PR DESCRIPTION
**Pull request by rbradford**
This will give us advanced notice of upcoming changes.

Signed-off-by: Rob Bradford <robert.bradford@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
@rbradford I fixed the warnings due to the beta toolchain. We should squash your commit with the one where I simply add `beta` to the test matrix. I was wondering, do we want to keep `stable` along with `beta` (since this is increasing the testing time)?

**Comment by rbradford** [comment]
> @rbradford I fixed the warnings due to the beta toolchain. We should squash your commit with the one where I simply add `beta` to the test matrix. I was wondering, do we want to keep `stable` along with `beta` (since this is increasing the testing time)?

Matrix jobs  on GH actions run in parallel. The complicated matrix stuff is so that the full workflow won't fail if the individual beta job fails.

**Comment by sboeuf** [comment]
>The complicated matrix stuff is so that the full workflow won't fail if the individual beta job fails.

Let's remove the complicated stuff as we don't want to merge some code that doesn't compile with `beta`, right?

**Comment by rbradford** [comment]
> > The complicated matrix stuff is so that the full workflow won't fail if the individual beta job fails.
> 
> Let's remove the complicated stuff as we don't want to merge some code that doesn't compile with `beta`, right?

The point is beta might change or give wrong results. So don't want to block unrelated PRs whilst beta gets fixed/we look into it.

**Comment by rbradford** [comment]
> > > The complicated matrix stuff is so that the full workflow won't fail if the individual beta job fails.
> > 
> > 
> > Let's remove the complicated stuff as we don't want to merge some code that doesn't compile with `beta`, right?
> 
> The point is beta might change or give wrong results. So don't want to block unrelated PRs whilst beta gets fixed/we look into it.

We previously had beta nightly in the matrix and then removed them for this very reason.

**Review by sboeuf — APPROVED** [review]

**Comment by sboeuf** [comment]
@rbradford PR's ready now, if you want to merge it :)

**Pull request merged**
