### PR TITLE
hypervisor: mshv: explicitly skip a few IO ports

### PR DESCRIPTION
**Pull request by liuw**
OVMF would use string IO on those ports. String IO has not been
implemented, so that leads to panics.

Since Cloud Hypervisor doesn't return anything useful from those IO
ports anyway, skip them explicitly in MSHV.

Leave a long-ish comment in code to explain the situation. We should
properly implement string IO once it becomes necessary.

Signed-off-by: Wei Liu <liuwe@microsoft.com>

### CODE REVIEW

**Review by sboeuf — APPROVED** [review]

**Comment by rbradford** [comment]
We do support debug port (0x402) under the "fwdebug" feature.

**Comment by liuw** [comment]
> We do support debug port (0x402) under the "fwdebug" feature.

Ah, I missed that. Let me check what needs to be done for that.

**Comment by liuw** [comment]
@rbradford fwdebug is not enabled by default and it is very limited. What is the long term plan for it? Is there going to be more sensible interface in the future?

**Comment by rbradford** [comment]
> @rbradford fwdebug is not enabled by default and it is very limited. What is the long term plan for it? Is there going to be more sensible interface in the future?

It's just a simple outb() used for edk2.

**Comment by liuw** [comment]
> > @rbradford fwdebug is not enabled by default and it is very limited. What is the long term plan for it? Is there going to be more sensible interface in the future?
> 
> It's just a simple outb() used for edk2.

Yes. I know that. :-)

I'm just trying to figure out how important to make it work _now_. If there is another better interface than its importance is low.

But I think its proper support is going to need the translate GVA code I'm working on, so I will skip that port in this patch anyway.

I will update the comment in code with the proper reasoning.

**Comment by rbradford** [comment]
I think it's fine to drop it if it's doing string output to that I/O port. I guess it's not just a simple byte via outb.

**Comment by liuw** [comment]
> I think it's fine to drop it if it's doing string output to that I/O port. I guess it's not just a simple byte via outb.

It is doing string IO.

**Review by sameo — APPROVED** [review]

**Pull request merged**
