### PR TITLE
More patches for unified binary -- part 3

### PR DESCRIPTION
**Pull request by liuw**

### CODE REVIEW

**Comment by liuw** [comment]
There are two failures

```
failures:
    parallel::test_vfio
    parallel::test_virtio_balloon_deflate_on_oom
```

I reran them locally. The first one could not work probably due to setup issue; the second one passed.

**Comment by liuw** [comment]
I tried again. At least the virtio_balloon_oom is always passing on my side.

Looking at the output from Jenkins in both failing tests the guests were launched successfully.

@rbradford any suggestion on how to debug further?

**Comment by rbradford** [comment]
> I tried again. At least the virtio_balloon_oom is always passing on my side.
> 
> Looking at the output from Jenkins in both failing tests the guests were launched successfully.
> 
> @rbradford any suggestion on how to debug further?

test_vfio is a hard one both due to the way the test works and that it involves nesting and is itself running in virtualization. I suggest creating an Azure D64s_v5 with 20_04-lts-gen2 and trying to recreate it there.

**Comment by rbradford** [comment]
@liuw Needs a rebase but then we can merge it.

**Pull request merged**
