### PR TITLE
[RFC] Switch to the rust-vmm vfio crate

### PR DESCRIPTION
**Pull request by sameo**
There's a [pending PR](https://github.com/rust-vmm/vfio-ioctls/pull/1) for the initial vfio crate implementation on rust-vmm. This PR is an experiment to see how it would look like to switch to it, and if it actually passes our CI.

The main change when switching to this crate would be about moving the VFIO PCI support under the PCI crate, making the PCI create depend on KVM.

### CODE REVIEW

**Comment by jiangliu** [comment]
Great to hear that the vfio_pci.rs has been moved into the PCI crate, I'm planning to do it just now:)

**Comment by sameo** [comment]
> Great to hear that the vfio_pci.rs has been moved into the PCI crate, I'm planning to do it just now:)

Let's see what others think about that move ;-)

**Comment by sboeuf** [comment]
@sameo 
I reviewed the PR, it looks mostly good to me. I have one concern about the first commit:
```
vfio: Move the PCI implementation to the PCI crate
```
By moving the `vfio_pci` bits into the `pci` crate, we're making the crate depending on the `vfio-ioctls` crate, which I feel is now the wrong direction in terms of dependency. If we follow this reorganization of the code, then this means `virtio_pci` should also live in the `pci` crate.
When I think of VFIO or virtio, I see the actual framework relying on a specific transport layer that they need to implement, based on some low level component. In this case, I see the `pci` crate as the low level component, that's why it doesn't feel natural to do this move.

I will test as soon as I get off the plane, as I want to validate both VFIO and VFIO with vIOMMU is working properly with this PR :)

**Comment by jiangliu** [comment]
> @sameo
> I reviewed the PR, it looks mostly good to me. I have one concern about the first commit:
> 
> ```
> vfio: Move the PCI implementation to the PCI crate
> ```
> 
> By moving the `vfio_pci` bits into the `pci` crate, we're making the crate depending on the `vfio-ioctls` crate, which I feel is now the wrong direction in terms of dependency. If we follow this reorganization of the code, then this means `virtio_pci` should also live in the `pci` crate.
> When I think of VFIO or virtio, I see the actual framework relying on a specific transport layer that they need to implement, based on some low level component. In this case, I see the `pci` crate as the low level component, that's why it doesn't feel natural to do this move.
> 
> I will test as soon as I get off the plane, as I want to validate both VFIO and VFIO with vIOMMU is working properly with this PR :)

We have organized the tree according to the top most bus visible from the guest VM side, and we treat virtio as a virtual bus. So the source code organization is:
1) PCI device passthrough as PCI device in pci crates,
2) virtio-pci transport layer in virtio crate,
3) PCI device passthrough as virtio-mmio device in virtio crate.

**Comment by sboeuf** [comment]
@jiangliu 
>We have organized the tree according to the top most bus visible from the guest VM side, and we treat virtio as a virtual bus. So the source code organization is:
>
>    1. PCI device passthrough as PCI device in pci crates,
>    2. virtio-pci transport layer in virtio crate,
>    3. PCI device passthrough as virtio-mmio device in virtio crate.

Well I'm not saying we cannot make it work, but it doesn't feel like the natural way to organize these crates IMO. It's not because you need some `pci` support for your VMM that you necessarily want to pull some VFIO dependency with it.
For me, top down, it should be:
- virtio -> virtio-pci -> pci
- virtio -> virtio-mmio -> mmio
- vfio -> vfio-pci -> pci
- vfio -> vfio-ccw -> ccw

**Comment by sboeuf** [comment]
@sameo FYI, I tested your PR with the quick fix https://github.com/cloud-hypervisor/cloud-hypervisor/pull/457 and I can confirm both VFIO and VFIO with vIOMMU are still working :)

**Comment by jiangliu** [comment]
> @jiangliu
> 
> > We have organized the tree according to the top most bus visible from the guest VM side, and we treat virtio as a virtual bus. So the source code organization is:
> > 
> > 1. PCI device passthrough as PCI device in pci crates,
> > 2. virtio-pci transport layer in virtio crate,
> > 3. PCI device passthrough as virtio-mmio device in virtio crate.
> 
> Well I'm not saying we cannot make it work, but it doesn't feel like the natural way to organize these crates IMO. It's not because you need some `pci` support for your VMM that you necessarily want to pull some VFIO dependency with it.
> For me, top down, it should be:
> 
> * virtio -> virtio-pci -> pci
> * virtio -> virtio-mmio -> mmio
> * vfio -> vfio-pci -> pci
> * vfio -> vfio-ccw -> ccw

Seems we have different opinions about the VFIO:)
With current design, VFIO is a mechanism to access hardware devices on host side.
And propose to build the relationship as:
* virtio -> virtio-pci -> pci on guest side -> software emulated pci backend
* virtio -> virtio-pci -> pci on guest side -> vfio -> vfio-pci -> pci on host side
* virtio -> virtio-mmio -> mmio on guest side -> software emulated mmio backend
* virtio -> virtio-mmio -> mmio on guest side -> vfio -> vfio-pci -> pci on host side
* pci on guest side -> vfio -> vfio-pci -> pci on host side
* pci on guest side -> vfio -> vfio-mdev -> pci on host side(not sure about this scenario)

Based on above scenarios, 
we may position the pci crate as to emulate pci on guest side, and the vfio-ioctls as to access hardware on host side.
So it may be ok to move the vfio-pci.rs into the pci crate because the vfio-pci.rs emulates(pass through) a guest PCI device by using a vfio-pci device on the host side.

**Comment by sameo** [comment]
@zhabinecho Could you please refresh that PR to now use the cloud-hypervisor/vfio-ioctls crate dragonball branch?

**Comment by zhabinecho** [comment]
> @zhabinecho Could you please refresh that PR to now use the cloud-hypervisor/vfio-ioctls crate dragonball branch?
Yeah, no problem :-)

**Comment by zhabinecho** [comment]
> @zhabinecho Could you please refresh that PR to now use the cloud-hypervisor/vfio-ioctls crate dragonball branch?

Okay, no problem :-)

**Comment by arronwy** [comment]
I have rebased this PR to use cloud-hypervisor vfio-ioctls crate dragonball branch. The cloud-hypervisor integration test of test_vfio passed successfully.  I have a question for VfioDmaMapping part which currently not covered in vfio-ioctls dragonball branch, should we submit VfioDmaMapping  and device DMA related patches to vfio-ioctls crate dragonball branch first?

**Comment by sameo** [comment]
@arronwy In order to actually switch to the vfio-ioctls crate, here is what I think should be done:


1. Add the `ExternalDmaMapping` trait to the `vfio-ioctls` crate
1. Implement `ExternalDmaMapping` through `VfioDmaMapping` in the `vfio-ioctls` crate 
1. Add commit 3acf9dfcf3d3c1de38708c59595f5d25417832fd to the `vfio-ioctls` crate
1. Add memory hotplug support (commit e4a034aef9631fd476afc60392204a4b715e1516) to the `vfio-ioctls` crate

All the above steps could be done through one PR against the `vfio-ioctls` dragonball branch.

Once the `vfio-ioctls` PR is merged, you will have to rebase this PR (#430) and add a commit to it for `vm-device` to replace its `vm-device` dependency with a `vfio-ioctls` one. That is fine, as we're thinking about moving the virtio devices implementation out of the vm-virtio crate and leaving the core virtio implementation only there.

cc @rbradford

**Comment by sameo** [comment]
This has been closed through PR #1268

**Pull request closed without merging**
