### PR TITLE
Improve Linux kernel boot time

### PR DESCRIPTION
**Pull request by sboeuf**
This pull request fixes both the IOAPIC and the MCFG table implementations to improve the guest kernel boot time.

### CODE REVIEW

**Review by rbradford — APPROVED** [review]
Cool. Did you validate against Windows?

**Comment by sboeuf** [comment]
@rbradford 
>Cool. Did you validate against Windows?

Oh no I forgot that, let me verify this before we merge this PR.

**Comment by rbradford** [comment]
@sboeuf I restarted the build to pickup the virtiofsd fix

**Comment by sboeuf** [comment]
@rbradford cool thanks for restarting the build!
FYI, I've just tested with Windows and it boots fine :)

**Comment by sboeuf** [comment]
It didn't get rebased on top of master, let me do that manually then.

**Comment by rbradford** [comment]
> It didn't get rebased on top of master, let me do that manually then.

There is no need to rebase. For every CI run the tip of master is merged into your PR.

**Pull request merged**
