### PR TITLE
build: Bump vmm-sys-util crate and its consumers

### PR DESCRIPTION
**Pull request by likebreath**
This patch bumps the following crates, including `kvm-bindings@0.7.0`\*,
`kvm-ioctls@0.16.0`\*\*, `linux-loader@0.11.0`, `versionize@0.2.0`,
`versionize_derive@0.1.6`\*\*\*, `vhost@0.10.0`,
`vhost-user-backend@0.13.1`, `virtio-queue@0.11.0`, `vm-memory@0.14.0`,
`vmm-sys-util@0.12.1`, and the latest of `vfio-bindings`, `vfio-ioctls`,
`mshv-bindings`,`mshv-ioctls`, and `vfio-user`.

\* A fork of the `kvm-bindings` crate is being used to support
serialization of various structs for migration [1]. Also, code changes
are made to accommodate the updated `struct xsave` from the Linux
kernel. Note: these changes related to `struct xsave` break
live-upgrade.

** The new `kvm-ioctls` crate introduced breaking changes for
the `get/set_one_reg` API on `aarch64` [2], so code changes are made to
the new APIs.

*** A fork of the `versionize_derive` crate is being used to support
versionize on packed structs [3].

[1] https://github.com/cloud-hypervisor/kvm-bindings/tree/ch-v0.7.0
[2] https://github.com/rust-vmm/kvm-ioctls/pull/223
[3] https://github.com/cloud-hypervisor/versionize_derive/tree/ch-0.1.6

Fixes: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/6072

Signed-off-by: Bo Chen <chen.bo@intel.com>

### CODE REVIEW

**Comment by rbradford** [comment]
Thank you for tackling this!

**Comment by rbradford** [comment]
> [1] https://github.com/cloud-hypervisor/kvm-bindings/tree/ch-v0.7.0-tdx-kernel-v5.19

Why did you go back from v6.3 to v5.19?

**Comment by likebreath** [comment]
> Thank you for tackling this!

Of course. The fuzzer issue is fixed on my end and I will need to look into issues from `aarch64`.

> > [1] https://github.com/cloud-hypervisor/kvm-bindings/tree/ch-v0.7.0-tdx-kernel-v5.19
> 
> Why did you go back from v6.3 to v5.19?

This is to keep the TDX support in the upstream Cloud Hypervisor that only works with this version of Linux kernel. This is the same as what we are doing right now with https://github.com/cloud-hypervisor/kvm-bindings/commits/ch-v0.6.0-tdx/ whose bindings are based on v5.12  while the kvm-bindings@v0.6.0 are based on v5.13.

I am working on enabling TDX for Cloud Hypervisor on a newer version of Linux kernel based with Canonical's Technical Preview stack [1]. Once this is done (estimated end of this quater), we can move the Linux kernel v6.3+. Also, we are trying to make TDX stack available as a part of Canonical's upcoming LTS release, e.g. Ubuntu 24.04, which we are looking at H2 this year.

In the meantime, this is the best solution that I came up with.

**Comment by likebreath** [comment]
> Also, changes are being made to accommodate the changes
> on the struct xsave from the Linux kernel.

@rbradford One more thing to mention. This causes test failures on live-upgrade. This is expected.  Please let me know your thoughts.

**Comment by rbradford** [comment]
I've looked through where we import symbols from kvm_bindings and I can't find any that are TDX specific. Are you sure we need to have modified bindings for TDX? Can you try without and if a constant or struct is missing just copy it in.

**Comment by likebreath** [comment]
> I've looked through where we import symbols from kvm_bindings and I can't find any that are TDX specific. Are you sure we need to have modified bindings for TDX? Can you try without and if a constant or struct is missing just copy it in.

@rbradford Here is one example [1]. The return of the `KVM_RUN` ioctl (e.g. `struct kvm_run`) was extended to have specific information about VM exit caused by TDX hyper-calls. We can't "copy it in" to Cloud Hypervisor code base, as API functions from `kvm-ioctl` are also using `struct kvm_run` extensively. I *may* manually instrument `kvm-bindings` crate for this bits, but I trust `bindgen` more than manual instrument from myself.

What's your concern of using a `kvm-bindings` based on v5.19 for now? From the x86 CI runner, it looks like it does not bring any functional differences.

[1] https://github.com/cloud-hypervisor/cloud-hypervisor/blob/7674196113d47d7b30e1fdaf7c86724bdb1d4345/hypervisor/src/kvm/mod.rs#L2142

**Comment by rbradford** [comment]
> > I've looked through where we import symbols from kvm_bindings and I can't find any that are TDX specific. Are you sure we need to have modified bindings for TDX? Can you try without and if a constant or struct is missing just copy it in.
> 
> @rbradford Here is one example [1]. The return of the `KVM_RUN` ioctl (e.g. `struct kvm_run`) was extended to have specific information about VM exit caused by TDX hyper-calls. We can't "copy it in" to Cloud Hypervisor code base, as API functions from `kvm-ioctl` are also using `struct kvm_run` extensively. I _may_ manually instrument `kvm-bindings` crate for this bits, but I trust `bindgen` more than manual instrument from myself.
> 
> What's your concern of using a `kvm-bindings` based on v5.19 for now? From the x86 CI runner, it looks like it does not bring any functional differences.
> 
> [1]
> 
> https://github.com/cloud-hypervisor/cloud-hypervisor/blob/7674196113d47d7b30e1fdaf7c86724bdb1d4345/hypervisor/src/kvm/mod.rs#L2142

This is the only code that requires the bindings - for consistency with the rest of the TDX code I think it would be better to carry our own versions. (See #6137)

My motivation for not using the modified bindings are:
* Ease with upgrading to new kernel versions (e.g. to support new architectures, new functionality)
* Easier crate upgrades
* Consistency with the rest of the TDX support - with the exception of the vmcall struct everything else is done using CH "owned" structures and constants.

And I think most importantly:
* Detaches the TDX kernel ABI from the version of kvm-bindings API - e.g. if we wanted to support newer or kernel ABI than the kernel API (this has been necessary in the past.)

**Comment by likebreath** [comment]
> This is the only code that requires the bindings - for consistency with the rest of the TDX code I think it would be better to carry our own versions. (See #6137)
> 
> My motivation for not using the modified bindings are:
> 
> * Ease with upgrading to new kernel versions (e.g. to support new architectures, new functionality)
> * Easier crate upgrades
> * Consistency with the rest of the TDX support - with the exception of the vmcall struct everything else is done using CH "owned" structures and constants.
> 
> And I think most importantly:
> 
> * Detaches the TDX kernel ABI from the version of kvm-bindings API - e.g. if we wanted to support newer or kernel ABI than the kernel API (this has been necessary in the past.)

Okay. I thought the practice for our TDX code is directly using data structures and constants from our kvm-bindings that specifically comes with TDX patches. Looks like it is a misunderstanding. 

Thanks for sending the PR. The code looks good to me. Just merged it. I believe this "copy-in" approach (e.g. carry our own versions of new data structures and constants) would work as long as we are only using constants, new data structure for "setters", and new data structure that is extended as a union member of the existing data structure for "getters" (e.g. the case for vmcall struct).

I agree detaching TDX kernel ABIs is a better way to go and good to see most of our code base is already doing that. I went through my patches for supporting newer version of TDX APIs along with new KVM APIs for guest memory support (expected to land at v6.8) [1]. I believe the "copy-in" approach would work, though some re-work is needed.

[1] https://github.com/torvalds/linux/commit/6c370dc65374db5afbc5c6c64c662f922a2555ad

**Comment by rbradford** [comment]
@likebreath In the long term when the ABI/API is stabilised all the locally defined contstants and structures can be removed and replaced with versions from the bindings.

**Review by rbradford — APPROVED** [review]
:rocket:

**Pull request merged**
