### PR TITLE
block_util: Align buffers for O_DIRECT

### LINKED ISSUE #3587: direct=on fails with hypervisor-fw based boot
```
marvin:~/src/cloud-hypervisor (main)$ target/debug/cloud-hypervisor --kernel ~/workloads/hypervisor-fw --disk path=~/workloads/focal-server-cloudimg-amd64-custom-20210609-0.raw,direct=on,_disable_io_uring=on --memory size=1G --cpus boot=1 --serial tty --console off -v
cloud-hypervisor: 2.0931ms: <vmm> INFO:vmm/src/lib.rs:1340 -- API request event: VmCreate(Mutex { data: VmConfig { cpus: CpusConfig { boot_vcpus: 1, max_vcpus: 1, topology: None, kvm_hyperv: false, max_phys_bits: 46, affinity: None }, memory: MemoryConfig { size: 1073741824, mergeable: false, hotplug_method: Acpi, hotplug_size: None, hotplugged_size: None, shared: false, hugepages: false, hugepage_size: None, prefault: false, zones: None }, kernel: Some(KernelConfig { path: "/home/rob/workloads/hypervisor-fw" }), initramfs: None, cmdline: CmdlineConfig { args: "" }, disks: Some([DiskConfig { path: Some("/home/rob/workloads/focal-server-cloudimg-amd64-custom-20210609-0.raw"), readonly: false, direct: true, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, poll_queue: true, rate_limiter_config: None, id: None, disable_io_uring: true, pci_segment: 0 }]), net: None, rng: RngConfig { src: "/dev/urandom", iommu: false }, balloon: None, fs: None, pmem: None, serial: ConsoleConfig { file: None, mode: Tty, iommu: false }, console: ConsoleConfig { file: None, mode: Off, iommu: false }, devices: None, user_devices: None, vsock: None, iommu: false, sgx_epc: None, numa: None, watchdog: false, platform: None }, poisoned: false, .. }, Sender { .. })
cloud-hypervisor: 2.629587ms: <vmm> INFO:vmm/src/lib.rs:1340 -- API request event: VmBoot(Sender { .. })
cloud-hypervisor: 3.613528ms: <vmm> INFO:vmm/src/memory_manager.rs:1476 -- Creating userspace mapping: 0 -> 7f1978000000 40000000, slot 0
cloud-hypervisor: 3.720616ms: <vmm> INFO:vmm/src/memory_manager.rs:1510 -- Created userspace mapping: 0 -> 7f1978000000 40000000
cloud-hypervisor: 3.778217ms: <vmm> INFO:vmm/src/vm.rs:544 -- Booting VM from config: Mutex { data: VmConfig { cpus: CpusConfig { boot_vcpus: 1, max_vcpus: 1, topology: None, kvm_hyperv: false, max_phys_bits: 46, affinity: None }, memory: MemoryConfig { size: 1073741824, mergeable: false, hotplug_method: Acpi, hotplug_size: None, hotplugged_size: None, shared: false, hugepages: false, hugepage_size: None, prefault: false, zones: None }, kernel: Some(KernelConfig { path: "/home/rob/workloads/hypervisor-fw" }), initramfs: None, cmdline: CmdlineConfig { args: "" }, disks: Some([DiskConfig { path: Some("/home/rob/workloads/focal-server-cloudimg-amd64-custom-20210609-0.raw"), readonly: false, direct: true, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, poll_queue: true, rate_limiter_config: None, id: None, disable_io_uring: true, pci_segment: 0 }]), net: None, rng: RngConfig { src: "/dev/urandom", iommu: false }, balloon: None, fs: None, pmem: None, serial: ConsoleConfig { file: None, mode: Tty, iommu: false }, console: ConsoleConfig { file: None, mode: Off, iommu: false }, devices: None, user_devices: None, vsock: None, iommu: false, sgx_epc: None, numa: None, watchdog: false, platform: None }, poisoned: false, .. }
cloud-hypervisor: 4.333853ms: <vmm> INFO:vmm/src/pci_segment.rs:92 -- Adding PCI segment: id=0, PCI MMIO config address: 0xe8000000, device area [0x100000000-0x7effffffff
cloud-hypervisor: 4.783015ms: <vmm> INFO:vmm/src/device_manager.rs:1945 -- Creating virtio-block device: DiskConfig { path: Some("/home/rob/workloads/focal-server-cloudimg-amd64-custom-20210609-0.raw"), readonly: false, direct: true, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, poll_queue: true, rate_limiter_config: None, id: Some("_disk0"), disable_io_uring: true, pci_segment: 0 }
cloud-hypervisor: 10.425185ms: <vmm> INFO:vmm/src/device_manager.rs:2030 -- Using synchronous RAW disk file
cloud-hypervisor: 10.450151ms: <vmm> INFO:virtio-devices/src/block.rs:438 -- Disk topology: DiskTopology { logical_block_size: 512, physical_block_size: 512, minimum_io_size: 512, optimal_io_size: 0 }
cloud-hypervisor: 10.515426ms: <vmm> INFO:vmm/src/device_manager.rs:2260 -- Creating virtio-rng device: RngConfig { src: "/dev/urandom", iommu: false }
cloud-hypervisor: 10.921134ms: <vmm> INFO:vmm/src/vm.rs:1968 -- Booting VM
cloud-hypervisor: 10.937937ms: <vmm> INFO:vmm/src/vm.rs:1000 -- Loading kernel
cloud-hypervisor: 11.052221ms: <vmm> INFO:vmm/src/vm.rs:1060 -- Kernel loaded: entry_addr = 0x11205e
cloud-hypervisor: 11.070234ms: <vmm> INFO:vmm/src/cpu.rs:682 -- Request to create new vCPUs: desired = 1, max = 1, allocated = 0, present = 0
cloud-hypervisor: 11.083599ms: <vmm> INFO:vmm/src/cpu.rs:648 -- Creating vCPU: cpu_id = 0
cloud-hypervisor: 11.29025ms: <vmm> INFO:vmm/src/cpu.rs:278 -- Configuring vCPU: cpu_id = 0
cloud-hypervisor: 13.870872ms: <vmm> INFO:vmm/src/acpi.rs:689 -- Generated ACPI tables: took 2471µs
cloud-hypervisor: 13.894002ms: <vmm> INFO:vmm/src/vm.rs:2017 -- Created ACPI tables: rsdp_addr = 0xa0000
cloud-hypervisor: 13.912809ms: <vmm> INFO:vmm/src/vm.rs:1071 -- Configuring system
cloud-hypervisor: 14.042867ms: <vmm> INFO:vmm/src/cpu.rs:890 -- Starting vCPUs: desired = 1, allocated = 1, present = 0
cloud-hypervisor: 14.253481ms: <vmm> INFO:vmm/src/cpu.rs:738 -- Starting vCPU: cpu_id = 0
Setting up 4 GiB identity mapping
Page tables setup

Booting with PVH Boot Protocol
Found PCI device vendor=8086 device=d57 in slot=0
Found PCI device vendor=1af4 device=1042 in slot=1
Found PCI device vendor=1af4 device=1044 in slot=2
PCI Device: 0:1.0 1af4:1042
Bar: type=MemorySpace32 address=e7f80000
Bar: type=MemorySpace32 address=0
Bar: type=MemorySpace32 address=0
Bar: type=MemorySpace32 address=0
Bar: type=MemorySpace32 address=0
Bar: type=MemorySpace32 address=0
cloud-hypervisor: 21.770353ms: <vcpu0> INFO:virtio-devices/src/transport/pci_device.rs:1051 -- _virtio-pci-_disk0: Needs activation; writing to activate event fd
cloud-hypervisor: 21.797021ms: <vcpu0> INFO:virtio-devices/src/transport/pci_device.rs:1056 -- _virtio-pci-_disk0: Needs activation; returning barrier
cloud-hypervisor: 21.821757ms: <vcpu0> INFO:vmm/src/vm.rs:432 -- Waiting for barrier
cloud-hypervisor: 21.807035ms: <vmm> INFO:vmm/src/lib.rs:1325 -- Trying to activate pending virtio devices: count = 1
cloud-hypervisor: 21.893469ms: <vmm> INFO:virtio-devices/src/transport/pci_device.rs:691 -- _virtio-pci-_rng: Device does not need activation
cloud-hypervisor: 21.976696ms: <vmm> INFO:virtio-devices/src/block.rs:519 -- Changing cache mode to writethrough
cloud-hypervisor: 22.216676ms: <vmm> INFO:virtio-devices/src/transport/pci_device.rs:687 -- _virtio-pci-_disk0: Waiting for barrier
cloud-hypervisor: 22.241007ms: <vmm> INFO:virtio-devices/src/transport/pci_device.rs:689 -- _virtio-pci-_disk0: Barrier released
cloud-hypervisor: 22.246828ms: <vcpu0> INFO:vmm/src/vm.rs:434 -- Barrier released
Virtio block device configured. Capacity: 4612096 sectors
cloud-hypervisor: 23.31538ms: <_disk0_q0> ERROR:virtio-devices/src/block.rs:307 -- Failed to process queue (submit): RequestExecuting(AsyncRead(ReadVectored(Os { code: 22, kind: InvalidInput, message: "Invalid argument" })))
```

Disabling io_uring has no impact. Booting with same disk image but direct kernel boot is fine. I suspect an alignment issue as O_DIRECT requires this. After investigation it might need to be punted to the https://github.com/cloud-hypervisor/rust-hypervisor-firmware issue tracker.

### PR DESCRIPTION
**Pull request by sboeuf**
Whenever the backing file of our virtio-block device is opened with
O_DIRECT, there's a requirement about the buffer address and size to be
aligned to the sector size.

We know virtio-block requests are sector aligned in terms of size, but
we must still check if the buffer address is. In case it's not, we
create an intermediate buffer that will be passed through the system
call. In case of a write operation, the content of the non-aligned
buffer must be copied beforehand, and in case of a read operation, the
content of the aligned buffer must be copied to the non-aligned one
after the operation has been completed.

Fixes #3587

Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
@rbradford please have a try on your side, but FWIW it's all fixed on my side.

**Review by rbradford — APPROVED** [review]
Add an integration test using O_DIRECT and hypervisor-fw?

**Comment by sboeuf** [comment]
> Add an integration test using O_DIRECT and hypervisor-fw?

Sounds good

**Comment by sboeuf** [comment]
@rbradford I fixed the integration with the copy we talked about.

**Review by rbradford — APPROVED** [review]

**Pull request merged**
