### PR TITLE
tests: First take on refactoring Windows tests

### PR DESCRIPTION
**Pull request by weltling**
This is the first step on handling #2520. This patch

- Recombines the common code into macros.
- Standardizes the test init/tear down.
- The VM start command is to contain as much as possible options that could be enabled at once.
- Adds extra macro for shutdown/reboot guest.

These all are trivial measures.

Signed-off-by: Anatol Belski <anbelski@linux.microsoft.com>

### CODE REVIEW

**Review by sboeuf — COMMENTED** [review]
The refactoring is nice, but could you use functions instead of macros? I always think macros are quite hard to read/follow, that's why I prefer the use of regular functions, unless we can't achieve what we need with a function.

**Comment by rbradford** [comment]
I think the macro usage makes it more complicated. What about defining a `WindowsGuest` guest struct with methods defined on that.

**Comment by weltling** [comment]
Thanks for the comments. My first approach was to create functions returning tuples, but that's where lifetime issues turned out. So then I've chosen macros, as in that case things stay in the same scope and optically the patch would be still small. Encapsulating into a struct should be fine. I'll rework this and come back with another proposal.

Thanks.

**Comment by sboeuf** [comment]
@weltling Any progress?

**Comment by weltling** [comment]
@sboeuf I did further play on this and there are issues that i think make the intend more troublesome than it looked like. To name some:

- The Guest struct expects `disk_config: &'a dyn DiskConfig`  which has to be on the same scope, so it can't be encapsulated cleanly.
- The `GuestCommand::new` can be encapsulated into a method, but the way we currently use it would unwrap `std::process::Child` as it's needed within the test
- Further on, `Output` is used to `child.wait_with_output()` which will cause child to be moved if passed to another method

Looking across the other existing tests, it seems that it's constructed under the same assumption. Namely, that things stay in the same scope. I was still looking at how these to be solved, but right now it means it's not possible to cleanly refactor Windows tests only this way. Fe making the `Guest` struct to own the `DiskConfig` member would need to touch any other test which is a huge change compared to the initial intend.

Macros seem the only simplest way right no to reduce the code duplication. I think for now it's convenient to leave this as is and close this PR, as growing the number of tests is much more critical ATM. There are still good points to pursue in the linked issue, a way to avoid fix timeouts while waiting for the system boot for example.

Thanks

**Comment by rbradford** [comment]
Closing as suggested.

**Pull request closed without merging**
