### PR TITLE
Speed up restore by mmap memory-ranges with MAP_PRIVATE

### PR DESCRIPTION
**Pull request by zhuangel**
Now cloud hypervisor save all guest memory into file <memory-ranges>, then fill guest memory with file <memroy-ranges> in restore. Current restore implementation is time costing, in my environment restore 512 MB memory will need 160ms+.

This PR introduce an optimize method, restore guest memory base mmap of memory-ranges file with MAP_PRIVATE, like COW in fork system call, VMs restored from same SNAP will share the memory-ranges for read access to guest memory, and lazy page allocation base COW in write access to guest memory.

The optimization does not support VM guest memory configured as shared mapping, such as vhost environment.

### CODE REVIEW

**Review by rbradford — CHANGES_REQUESTED** [review]
We've been here before. This is a bad idea - see #4805. Using `MAP_PRIVATE` breaks vfio, vfio-user, vhost-user and huge pages.

**Comment by zhuangel** [comment]
> We've been here before. This is a bad idea - see #4805. Using `MAP_PRIVATE` breaks vfio, vfio-user, vhost-user and huge pages.

Current solution will be disabled when memory or memory zone is configured as shared, I didn't have a solution works for all configurations, such as VM with VFIO or VHOST is enabled.

The current optimization scheme can greatly reduce latency in the snap recovery and save a lot of memory. Specially in high-density scenarios. With our configuration scenario, about 33 MB memory for cold start VM can be reduced to about 6 MB, and 1000 VMs can save 27 GB.

**Comment by rbradford** [comment]
The correct solution to the problem is to load the memory from the backing file on-demand (and maybe a slow trickle in the background) by using userfaultfd (https://www.kernel.org/doc/html/v5.0/admin-guide/mm/userfaultfd.html) this then will no compromise any of the functionality of Cloud Hypervisor.

**Comment by zhuangel** [comment]
> and maybe a slow trickle in the background

Thanks, Rob, the userfaultfd solution sounds more general, but I am not sure whether it will share page cache for read page fault, and the performance for restore (the page fault path is longer and need another process/thread to fix the page fault).  

Current solution limited just to non-shared memory, but gain better restore performance.

**Comment by zhuangel** [comment]
Hi @rbradford I will do more investigation about userfault fd, then come back if there is a better way to implement the optimization, now I will close this PR, thanks.

**Pull request closed without merging**
