### PR TITLE
virtio-devices: Remove VIRTIO_F_RING_PACKED from default virtio features

### PR DESCRIPTION
**Pull request by arafatms**
The cloud hypervisor tells the VM and the backend to support the PACKED_RING feature,
but it actually processes various variables according to the split ring logic, such
as last_avail_index. Eventually it will cause the following error (SPDK as an example):

    vhost.c: 516:vhost_vq_packed_ring_enqueue: *ERROR*: descriptor has been used before
    vhost_blk.c: 596:process_blk_task: *ERROR*: ====== Task 0x200113784640 req_idx 0 failed ======
    vhost.c: 629:vhost_vring_desc_payload_to_iov: *ERROR*: gpa_to_vva((nil)) == NULL

Signed-off-by: Arafatms <arafatms@outlook.com>

### CODE REVIEW

**Review by sboeuf — APPROVED** [review]
Since the vhost-user backend is really the one handling the queues requests from the guest, I thought we could enable `VIRTIO_F_RING_PACKED` so that we wouldn't prevent the packed queues from being used. But I guess it's a bit more complicated than that, as the queues are still setup/activated through the VMM.

**Comment by sboeuf** [comment]
@arafatms thanks for the PR, please make sure to fix the clippy/rustfmt issues before we can merge this PR.

**Comment by arafatms** [comment]
@sboeuf got it. I will make a patch to support VIRTIO_F_RING_PACKED in the near future.

**Comment by rbradford** [comment]
> @sboeuf got it. I will make a patch to support VIRTIO_F_RING_PACKED in the near future.

Not sure it makes sense; `VIRTIO_F_RING_PACKED` was added for hardware devices that expose virtio directly.

**Comment by rbradford** [comment]
That being said: QEMU says it improved performance for them: https://patchew.org/QEMU/20200522171726.648279-1-stefanha@redhat.com/

**Comment by arafatms** [comment]
@rbradford Yeap. After my previous test, VIRTIO_F_RING_PACKED can improve performance by about 10%.

**Comment by sboeuf** [comment]
10% is good but we need to understand/see what the changes will imply from a code perspective. We don't want to increase the complexity too much if the gain is not very important. Anyway, I think you should open a dedicated issue so that we could discuss about it there.

**Pull request merged**
