### PR TITLE
tests: Move to use Jammy guest image for `test_vfio_user`

### PR DESCRIPTION
**Pull request by likebreath**
Fixes: #3495

Signed-off-by: Bo Chen <chen.bo@intel.com>

### CODE REVIEW

**Comment by rbradford** [comment]
@likebreath Unfortunately looks like you've got a seccomp filter issue.

**Comment by likebreath** [comment]
> Unfortunately looks like you've got a seccomp filter issue.

Yeah, just realized I only ran with `--seccomp false` locally. Issue should be fixed now. The added syscall should be from Seb's PR on connection shutdown of the vfio-user socket.

**Review by rbradford — APPROVED** [review]

**Review by sboeuf — COMMENTED** [review]
Looks good, but why do you enable this test only for `x86_64`?

**Comment by likebreath** [comment]
@michael2012z @MrXinWang Would you please help take a look at the documentation for custom image [here](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/custom-image.md) and let me know if that's up-to-date for `aarch64`? 

I wanted to make a custom image of Jammy for `aarch64` to experiment with the adjusted `test_vfio_user` test. Thank you.

**Comment by rbradford** [comment]
> @michael2012z @MrXinWang Would you please help take a look at the documentation for custom image [here](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/custom-image.md) and let me know if that's up-to-date for `aarch64`?
> 
> I wanted to make a custom image of Jammy for `aarch64` to experiment with the adjusted `test_vfio_user` test. Thank you.

Those instructions are correct (I built the last aarch64 image) although I always find it easier to use `kpartx` rather than doing the sectors on the mount manually.

**Comment by likebreath** [comment]
The test is now also enabled for `aarch64` and passed from its first run. I will force push a few more times later today to get an idea of how stable it is. Assuming it looks promising, we will start a periodic CI on this PR tomorrow.

**Comment by michael2012z** [comment]
> The test is now also enabled for `aarch64` and passed from its first run. I will force push a few more times later today to get an idea of how stable it is. Assuming it looks promising, we will start a periodic CI on this PR tomorrow.

Excellent! Thank you for letting it happen on aarch64 as well.

**Comment by likebreath** [comment]
@sboeuf @rbradford Can you please start a periodic CI job for this PR? It looks fairly promising that the issue (with vfio-user and spdk/nvme) is gone with this change.

All the past 8 CI jobs passed for `test_vfio_user` (last 3 jobs include `aarch64`), while there were some unrelated flaky test failures (e.g. test_vhost_user_blk_default, test_vfio, test_ovs_dpdk).

**Comment by sboeuf** [comment]
>@sboeuf @rbradford Can you please start a periodic CI job for this PR? It looks fairly promising that the issue (with vfio-user and spdk/nvme) is gone with this change.

Done!

**Comment by rbradford** [comment]
No failures from `test_vfio_user` on this PR so I think we should go ahead and merge it.

**Pull request merged**
