### PR TITLE
Migrate integration image to Ubuntu 22.04

### PR DESCRIPTION
**Pull request by praveen-pk**
Integration test's docker image is currently based on 20.04. This commit
migrates the docker image to 22.04. Ubuntu 22.04 has a larger collection
of packages and allows for easier extension and maintenance of the integration
tests in cloud-hypervisor.

Signed-off-by: Praveen K Paladugu <prapal@linux.microsoft.com>

### CODE REVIEW

**Review by likebreath — COMMENTED** [review]
Were you able to build the new version of spdk (e.g. v22.01.2) on Ubuntu 22.04 without modifying its source code (particularly `./scripts/pkgdep`)? Looks like the docker image failed to build due to `spdk` dependency installations:

```
[linux/amd64 10/11] RUN if [ "amd64" = "amd64" ]; then        git clone https://github.com/spdk/spdk        && cd spdk        && git checkout v22.01.2        && git submodule update --init        && apt-get update        && ./scripts/pkgdep.sh        && apt-get clean        && ./configure --with-vfio-user        && make -j `nproc`        && mkdir /usr/local/bin/spdk-nvme        && cp ./build/bin/nvmf_tgt /usr/local/bin/spdk-nvme        && cp ./scripts/rpc.py /usr/local/bin/spdk-nvme        && cp -r ./python/spdk/ /usr/local/bin/spdk-nvme        && cd .. && rm -rf spdk; fi:

#17 44.50 Reading state information...
#17 44.51 Package python is not available, but is referred to by another package.
#17 44.51 This may mean that the package is missing, has been obsoleted, or
#17 44.51 is only available from another source
#17 44.51 However the following packages replace it:
#17 44.51   2to3 python2-minimal python2 dh-python python-is-python3
#17 44.51 
#17 44.51 E: Package 'python' has no installation candidate
#17 44.51 Error!
```

**Comment by praveen-pk** [comment]
common_parallel::test_vfio_user is failing. Will check locally and update.

**Comment by praveen-pk** [comment]
Of the failures, I am focusing on `live_migration::live_migration_sequential::test_live_migration_ovs_dpdk` now.

**Comment by praveen-pk** [comment]
I had some initial success with compiling swtpm in 20.04 image. I will continue down that path. I am closing this PR for now.

**Pull request closed without merging**
