### PR TITLE
Add IOPS tests to performance metrics

### PR DESCRIPTION
**Pull request by liuw**

### CODE REVIEW

**Review by likebreath — APPROVED** [review]
Changes are looking good. 

Not sure if the metrics visualization scripts needs to be updated with the new tests. @rbradford

**Review by sboeuf — APPROVED** [review]

**Comment by rbradford** [comment]
> Changes are looking good.
> 
> Not sure if the metrics visualization scripts needs to be updated with the new tests. @rbradford

Nope, the list of tests is generated dynamically based on the test names that are seen.

**Review by rbradford — APPROVED** [review]
My only small concern is that this might increase the metrics test running time and lead t backlogs. Unfortunately the metrics system is unavailable right now so we won't know if this is an issue until that comes back.

**Comment by liuw** [comment]
> My only small concern is that this might increase the metrics test running time and lead t backlogs. Unfortunately the metrics system is unavailable right now so we won't know if this is an issue until that comes back.

How often does it run in upstream? Internally we run this once per day, overnight. Having a few more tests isn't a concern in that model.

Perhaps the infrastructure can filter out the tests to save some time?

**Pull request merged**
