### PR TITLE
virtio-devices: block: Replace use of HashMap for inflight requests

### PR DESCRIPTION
**Pull request by rbradford**
During analysis of the asynchrous block I/O handling it was observed
that the majority of the time the completion events occur in the same
order as submissions. Further the maximum number of inflight requests
during the boot time is much lower than the size of the queue.

Through the use of a double ended queue (VecDequeue) with a reasonable
pre-allocation capacity we can have O(1) allocation free addition of
items to the list of inflight requests and mostly O(1) matching of
completed requests to submissions.

Signed-off-by: Rob Bradford <robert.bradford@intel.com>

### CODE REVIEW

**Review by likebreath — COMMENTED** [review]
Given the number of inflight requests are very small as you measured, it makes sense to me that using a Dequeue is more efficient than using a Hashmap for boot time. 

If I am not mistaken, these two optimizations (using Dequeue + pre-allocation with "64" entries) are mostly for boot-time. I wonder how would these optimizations impact the block device performance other than boot-time?

**Comment by sboeuf** [comment]
@rbradford if you don't observe any performance regression when running fio tests, then let's merge this PR. The enhancement makes lots of sense given the input you've provided.

**Comment by rbradford** [comment]
I ran metrics and there was no regressions.

**Review by sboeuf — APPROVED** [review]
:+1:

**Pull request merged**
