### PR TITLE
hypervisor: use proper doc tests for examples

### PR DESCRIPTION
**Pull request by alyssais**
It seems like these examples were always intended to be doctests, since there are lines marked with "#" so that they are excluded from the generated documentation, but they were not recognised as doc tests because they were not formatted correctly.

The code needed some adjustments so that it would actually compile and run as doctests.

### CODE REVIEW

**Review by rbradford — APPROVED** [review]
I don't think that documentation is particularly enlightening but it's better that they work than not! Thank you for your PR.

**Review by likebreath — COMMENTED** [review]
We should also add the doctest as a part of our GitHub action. Looks like a good addition to: https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/.github/workflows/build.yaml?

**Comment by alyssais** [comment]
I don't think we can run the doctests on GitHub Actions, because they require KVM or MSHV to be available.  It would make sense to _build_ them, but I'm not sure if it's possible to get Cargo to build doctests without running them.  Do you know?

**Comment by likebreath** [comment]
> I'm not sure if it's possible to get Cargo to build doctests without running them. 

Didn't know this. Thanks for clarifying. Then we will have to build and run them in our CI pipeline, say from https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/scripts/run_unit_tests.sh?

**Review by rbradford — APPROVED** [review]

**Pull request merged**
