### PR TITLE
build: Move Jenkins workers over to jammy

### PR DESCRIPTION
**Pull request by rbradford**
Fixes: #3862

Signed-off-by: Rob Bradford <robert.bradford@intel.com>

### CODE REVIEW

**Comment by rbradford** [comment]
```
[   30.606094] bash[1411]: cloud-hypervisor: 27.927297ms: <vmm> ERROR:/usr/local/rust/git/checkouts/vfio-3ea6ca0c73c7450b/f75a77c/crates/vfio-ioctls/src/vfio_device.rs:687 -- Could not get region #8 info
[   30.606515] bash[1411]: cloud-hypervisor: 28.46876ms: <vmm> WARN:/usr/local/rust/git/checkouts/vfio-3ea6ca0c73c7450b/f75a77c/crates/vfio-ioctls/src/vfio_device.rs:552 -- Could not get VFIO IRQ info for index 3
[   30.768993] bash[1411]: cloud-hypervisor: 189.422994ms: <vmm> ERROR:/usr/local/rust/git/checkouts/vfio-3ea6ca0c73c7450b/f75a77c/crates/vfio-ioctls/src/vfio_device.rs:687 -- Could not get region #8 info
[   30.769351] bash[1411]: cloud-hypervisor: 189.678325ms: <vmm> WARN:/usr/local/rust/git/checkouts/vfio-3ea6ca0c73c7450b/f75a77c/crates/vfio-ioctls/src/vfio_device.rs:552 -- Could not get VFIO IRQ info for index 3
[   30.774980] bash[1411]: cloud-hypervisor: 197.406284ms: <vmm> ERROR:/usr/local/rust/git/checkouts/vfio-3ea6ca0c73c7450b/f75a77c/crates/vfio-ioctls/src/vfio_device.rs:687 -- Could not get region #8 info
[   30.775286] bash[1411]: cloud-hypervisor: 197.753077ms: <vmm> WARN:/usr/local/rust/git/checkouts/vfio-3ea6ca0c73c7450b/f75a77c/crates/vfio-ioctls/src/vfio_device.rs:552 -- Could not get VFIO IRQ info for index 3
[   30.785414] bash[1411]: cloud-hypervisor: 207.647439ms: <vcpu0> ERROR:vmm/src/cpu.rs:1020 -- VCPU generated error: VcpuRun(Failed to run vcpu: Unexpected exit reason on vcpu run: FailEntry
```

@sboeuf I think that the VFIO messages are to be expected? But this last one seems interesting...

**Comment by sboeuf** [comment]
> ```
> [   30.606094] bash[1411]: cloud-hypervisor: 27.927297ms: <vmm> ERROR:/usr/local/rust/git/checkouts/vfio-3ea6ca0c73c7450b/f75a77c/crates/vfio-ioctls/src/vfio_device.rs:687 -- Could not get region #8 info
> [   30.606515] bash[1411]: cloud-hypervisor: 28.46876ms: <vmm> WARN:/usr/local/rust/git/checkouts/vfio-3ea6ca0c73c7450b/f75a77c/crates/vfio-ioctls/src/vfio_device.rs:552 -- Could not get VFIO IRQ info for index 3
> [   30.768993] bash[1411]: cloud-hypervisor: 189.422994ms: <vmm> ERROR:/usr/local/rust/git/checkouts/vfio-3ea6ca0c73c7450b/f75a77c/crates/vfio-ioctls/src/vfio_device.rs:687 -- Could not get region #8 info
> [   30.769351] bash[1411]: cloud-hypervisor: 189.678325ms: <vmm> WARN:/usr/local/rust/git/checkouts/vfio-3ea6ca0c73c7450b/f75a77c/crates/vfio-ioctls/src/vfio_device.rs:552 -- Could not get VFIO IRQ info for index 3
> [   30.774980] bash[1411]: cloud-hypervisor: 197.406284ms: <vmm> ERROR:/usr/local/rust/git/checkouts/vfio-3ea6ca0c73c7450b/f75a77c/crates/vfio-ioctls/src/vfio_device.rs:687 -- Could not get region #8 info
> [   30.775286] bash[1411]: cloud-hypervisor: 197.753077ms: <vmm> WARN:/usr/local/rust/git/checkouts/vfio-3ea6ca0c73c7450b/f75a77c/crates/vfio-ioctls/src/vfio_device.rs:552 -- Could not get VFIO IRQ info for index 3
> [   30.785414] bash[1411]: cloud-hypervisor: 207.647439ms: <vcpu0> ERROR:vmm/src/cpu.rs:1020 -- VCPU generated error: VcpuRun(Failed to run vcpu: Unexpected exit reason on vcpu run: FailEntry
> ```
> 
> @sboeuf I think that the VFIO messages are to be expected? But this last one seems interesting...

That's indeed very interesting. I can't think of a good reason why VFIO tests would start failing because of the move to Jammy. Something to investigate...

**Comment by rbradford** [comment]
I was able to reproduce this 2 levels of nesting on an Azure VM (so 3 levels in total) when running with the 5.15 kernel that Azure on Jammy ships with.

**Comment by rbradford** [comment]
> > I was able to reproduce this 2 levels of nesting on an Azure VM (so 3 levels in total) when running with the 5.15 kernel that Azure on Jammy ships with.
> 
> And did you run into any issue?

Yes, I had the same issue. i.e. HyperV-KVM-KVM fails but KVM-KVM-KVM works.

**Comment by sboeuf** [comment]
> > > I was able to reproduce this 2 levels of nesting on an Azure VM (so 3 levels in total) when running with the 5.15 kernel that Azure on Jammy ships with.
> > 
> > 
> > And did you run into any issue?
> 
> Yes, I had the same issue. i.e. HyperV-KVM-KVM fails but KVM-KVM-KVM works.

Where did you test the KVM-KVM-KVM case? On your local machine or some baremetal environment?

And about the Azure case (HyperV-KVM-KVM), what can we do about it? Did you find a bug opened for that?

**Comment by rbradford** [comment]
> > > > I was able to reproduce this 2 levels of nesting on an Azure VM (so 3 levels in total) when running with the 5.15 kernel that Azure on Jammy ships with.
> > > 
> > > 
> > > And did you run into any issue?
> > 
> > 
> > Yes, I had the same issue. i.e. HyperV-KVM-KVM fails but KVM-KVM-KVM works.
> 
> Where did you test the KVM-KVM-KVM case? On your local machine or some baremetal environment?
> 

Yes locally.

> And about the Azure case (HyperV-KVM-KVM), what can we do about it? Did you find a bug opened for that?

I have no idea where such a bug could be asked. It's a regression vs the 5.13 kernel in focal. @liuw Perhaps you have an idea?

**Comment by liuw** [comment]
> > > > > I was able to reproduce this 2 levels of nesting on an Azure VM (so 3 levels in total) when running with the 5.15 kernel that Azure on Jammy ships with.
> > > > 
> > > > 
> > > > And did you run into any issue?
> > > 
> > > 
> > > Yes, I had the same issue. i.e. HyperV-KVM-KVM fails but KVM-KVM-KVM works.
> > 
> > 
> > Where did you test the KVM-KVM-KVM case? On your local machine or some baremetal environment?
> 
> Yes locally.
> 
> > And about the Azure case (HyperV-KVM-KVM), what can we do about it? Did you find a bug opened for that?
> 
> I have no idea where such a bug could be asked. It's a regression vs the 5.13 kernel in focal. @liuw Perhaps you have an idea?

I don't have a clear idea. Perhaps the 5.15 kernel is trying to use some new fancy features. If you have logs available I will try to ask around.

**Comment by rbradford** [comment]
> > > > > > I was able to reproduce this 2 levels of nesting on an Azure VM (so 3 levels in total) when running with the 5.15 kernel that Azure on Jammy ships with.
> > > > > 
> > > > > 
> > > > > And did you run into any issue?
> > > > 
> > > > 
> > > > Yes, I had the same issue. i.e. HyperV-KVM-KVM fails but KVM-KVM-KVM works.
> > > 
> > > 
> > > Where did you test the KVM-KVM-KVM case? On your local machine or some baremetal environment?
> > 
> > 
> > Yes locally.
> > > And about the Azure case (HyperV-KVM-KVM), what can we do about it? Did you find a bug opened for that?
> > 
> > 
> > I have no idea where such a bug could be asked. It's a regression vs the 5.13 kernel in focal. @liuw Perhaps you have an idea?
> 
> I don't have a clear idea. Perhaps the 5.15 kernel is trying to use some new fancy features. If you have logs available I will try to ask around.

You get a `KVM_EXIT_FAIL_ENTRY` when you try and run the vCPU with `hardware_entry_failure_reason = 7`

I'm going to close this PR (Jenkins will re-run all PRs as part of if its regular scan) so that it doesn't waste resources but we can continue the conversation.

**Comment by liuw** [comment]
> 
> You get a `KVM_EXIT_FAIL_ENTRY` when you try and run the vCPU with `hardware_entry_failure_reason = 7`
> 

I saw that. That's too little information to tell though. If there is a way to grab dmesg that would be great.

I know 5.15 contains some nested virtualization enhancements for AMD. Looking at the log in the CI I can see `kvm.intel_nested=1` so the AMD enhancement is probably not relevant.

**Comment by rbradford** [comment]
@liuw 

From the "host" (i.e. the Azure VM)

```
[ 1481.600386] WARNING: CPU: 4 PID: 7641 at arch/x86/kvm/vmx/nested.c:4563 nested_vmx_vmexit+0x70d/0x790 [kvm_intel]
[ 1481.600403] Modules linked in: binfmt_misc xt_tcpudp nft_counter xt_owner xt_conntrack nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 nft_compat nf_tables libcrc32c nfnetlink udf crc_itu_t mlx5_ib ib_uverbs nls_iso8859_1 ib_core mlx5_core tls kvm_intel mlxfw psample kvm joydev hid_generic hid_hyperv hv_netvsc hid crct10dif_pclmul crc32_pclmul hyperv_fb ghash_clmulni_intel serio_raw hyperv_keyboard aesni_intel efi_pstore crypto_simd cryptd dm_multipath scsi_dh_rdac scsi_dh_emc scsi_dh_alua sch_fq_codel ipmi_devintf ipmi_msghandler drm msr i2c_core ip_tables x_tables autofs4
[ 1481.600427] CPU: 4 PID: 7641 Comm: vcpu2 Not tainted 5.15.0-1008-azure #9-Ubuntu
[ 1481.600429] Hardware name: Microsoft Corporation Virtual Machine/Virtual Machine, BIOS Hyper-V UEFI Release v4.1 07/22/2021
[ 1481.600430] RIP: 0010:nested_vmx_vmexit+0x70d/0x790 [kvm_intel]
[ 1481.600436] Code: 01 0f 85 55 fa ff ff be 10 40 00 00 48 c7 c7 a8 fc 58 c0 c6 05 01 34 02 00 01 e8 87 d9 0c e9 0f 0b e9 36 fa ff ff 0f 0b eb 98 <0f> 0b e9 28 fd ff ff 44 0f b6 35 e2 33 02 00 41 80 fe 01 0f 87 0b
[ 1481.600437] RSP: 0018:ff3d8f7441b77b98 EFLAGS: 00010297
[ 1481.600439] RAX: 0000000000000000 RBX: 000000000000dead RCX: 00000000b5a06dfa
[ 1481.600440] RDX: ff1111f10bd3f000 RSI: 0000000000000283 RDI: 0000000000004400
[ 1481.600441] RBP: ff3d8f7441b77bc8 R08: ff1111f61fd21e60 R09: 0000000000000000
[ 1481.600441] R10: ff3d8f74407f3dd8 R11: ff1111eeb9120000 R12: ff1111eec1fdd500
[ 1481.600442] R13: ff1111ee80ac2000 R14: 0000000000000000 R15: 0000000000000000
[ 1481.600443] FS:  00007f688b369640(0000) GS:ff1111f61fd00000(0000) knlGS:0000000000000000
[ 1481.600445] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 1481.600446] CR2: 0000000000000000 CR3: 0000000142640006 CR4: 0000000000373ee0
[ 1481.600447] Call Trace:
[ 1481.600449]  <TASK>
[ 1481.600451]  nested_vmx_reflect_vmexit+0x10b/0x440 [kvm_intel]
[ 1481.600457]  __vmx_handle_exit+0xef/0x670 [kvm_intel]
[ 1481.600462]  ? vmx_vcpu_run+0x2d5/0xcb0 [kvm_intel]
[ 1481.600467]  vmx_handle_exit+0x12/0x50 [kvm_intel]
[ 1481.600472]  vcpu_enter_guest+0x83a/0xfd0 [kvm]
[ 1481.600516]  ? vmx_check_nested_events+0x1b8/0x3f0 [kvm_intel]
[ 1481.600524]  vcpu_run+0x5e/0x240 [kvm]
[ 1481.600560]  kvm_arch_vcpu_ioctl_run+0xd7/0x550 [kvm]
[ 1481.600597]  kvm_vcpu_ioctl+0x29a/0x6d0 [kvm]
[ 1481.600631]  ? __fget_files+0x86/0xc0
[ 1481.600634]  __x64_sys_ioctl+0x91/0xc0
[ 1481.600637]  do_syscall_64+0x5c/0xc0
[ 1481.600640]  ? vfs_write+0xc3/0x260
[ 1481.600643]  ? fput+0x13/0x20
[ 1481.600644]  ? ksys_write+0xce/0xe0
[ 1481.600651]  ? exit_to_user_mode_prepare+0x49/0x110
[ 1481.600653]  ? syscall_exit_to_user_mode+0x17/0x40
[ 1481.600655]  ? do_syscall_64+0x69/0xc0
[ 1481.600657]  ? syscall_exit_to_user_mode+0x17/0x40
[ 1481.600659]  ? do_syscall_64+0x69/0xc0
[ 1481.600660]  ? do_syscall_64+0x69/0xc0
[ 1481.600662]  ? do_syscall_64+0x69/0xc0
[ 1481.600663]  ? sysvec_hyperv_stimer0+0x4e/0x90
[ 1481.600665]  ? asm_sysvec_hyperv_stimer0+0xa/0x20
[ 1481.600667]  entry_SYSCALL_64_after_hwframe+0x44/0xae
[ 1481.600670] RIP: 0033:0x7f688becdaff
[ 1481.600672] Code: 00 48 89 44 24 18 31 c0 48 8d 44 24 60 c7 04 24 10 00 00 00 48 89 44 24 08 48 8d 44 24 20 48 89 44 24 10 b8 10 00 00 00 0f 05 <41> 89 c0 3d 00 f0 ff ff 77 1f 48 8b 44 24 18 64 48 2b 04 25 28 00
[ 1481.600673] RSP: 002b:00007f688b3666b0 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
[ 1481.600675] RAX: ffffffffffffffda RBX: 000055fba79eb880 RCX: 00007f688becdaff
[ 1481.600680] RDX: 0000000000000000 RSI: 000000000000ae80 RDI: 000000000000005c
[ 1481.600682] RBP: 0000000000000000 R08: 0000000000000000 R09: 0000000000000000
[ 1481.600682] R10: 000000000000007e R11: 0000000000000246 R12: 00007f68840458e0
[ 1481.600684] R13: 000000000000000e R14: 00007f688b167000 R15: 00007f6884041e80
[ 1481.600686]  </TASK>
```

**Comment by rbradford** [comment]
@liuw I also have debugging from the next level of VM:

```
[   58.012471] VMCS 00000000444185c0, last attempted VM-entry on CPU 3
[   58.015288] *** Guest State ***
[   58.017897] CR0: actual=0x0000000000000021, shadow=0x0000000000000001, gh_mask=fffffffffffffff7
[   58.022522] CR4: actual=0x0000000000002040, shadow=0x0000000000000000, gh_mask=fffffffffffef871
[   58.025900] CR3 = 0x0000000000000000
[   58.028553] PDPTR0 = 0x0000000000000000  PDPTR1 = 0x0000000000000000
[   58.032683] PDPTR2 = 0x0000000000000000  PDPTR3 = 0x0000000000000000
[   58.036501] RSP = 0x0000000000000000  RIP = 0x0000000000111bfe
[   58.040336] RFLAGS=0x00000002         DR7 = 0x0000000000000400
[   58.042927] Sysenter RSP=0000000000000000 CS:RIP=0000:0000000000000000
[   58.047171] CS:   sel=0x0008, attr=0x0c09b, limit=0xffffffff, base=0x0000000000000000
[   58.051891] DS:   sel=0x0010, attr=0x0c093, limit=0xffffffff, base=0x0000000000000000
[   58.056618] SS:   sel=0x0010, attr=0x0c093, limit=0xffffffff, base=0x0000000000000000
[   58.061585] ES:   sel=0x0010, attr=0x0c093, limit=0xffffffff, base=0x0000000000000000
[   58.065047] FS:   sel=0x0010, attr=0x0c093, limit=0xffffffff, base=0x0000000000000000
[   58.069855] GS:   sel=0x0010, attr=0x0c093, limit=0xffffffff, base=0x0000000000000000
[   58.074785] GDTR:                           limit=0x0000001f, base=0x0000000000000500
[   58.079327] LDTR: sel=0x0000, attr=0x00082, limit=0x0000ffff, base=0x0000000000000000
[   58.083937] IDTR:                           limit=0x00000007, base=0x0000000000000520
[   58.087209] TR:   sel=0x0018, attr=0x0008b, limit=0x00000067, base=0x0000000000000000
[   58.090164] EFER= 0x0000000000000000
[   58.092789] PAT = 0x0007040600070406
[   58.096702] DebugCtl = 0x0000000000000000  DebugExceptions = 0x0000000000000000
[   58.100963] Interruptibility = 00000000  ActivityState = 00000000
[   58.103442] *** Host State ***
[   58.104744] RIP = 0xffffffffc0b9bbf0  RSP = 0xff5790b9008efba0
[   58.107183] CS=0010 SS=0018 DS=0000 ES=0000 FS=0000 GS=0000 TR=0040
[   58.112255] FSBase=00007f189db76640 GSBase=ff3bddcb77d80000 TRBase=fffffe00000b4000
[   58.117625] GDTBase=fffffe00000b2000 IDTBase=fffffe0000000000
[   58.119972] CR0=0000000080050033 CR3=0000000108e72004 CR4=0000000000373ee0
[   58.122928] Sysenter RSP=fffffe00000b4000 CS:RIP=0010:ffffffffa84015f0
[   58.126967] EFER= 0x0000000000000d01
[   58.129705] PAT = 0x0407050600070106
[   58.132375] *** Control State ***
[   58.133749] PinBased=0000007f CPUBased=b5a06dfa SecondaryExec=021010aa
[   58.137721] EntryControls=0000d1ff ExitControls=002befff
[   58.139955] ExceptionBitmap=00060042 PFECmask=00000000 PFECmatch=00000000
[   58.142854] VMEntry: intr_info=00000000 errcode=00000000 ilen=00000000
[   58.147836] VMExit: intr_info=00000000 errcode=00000000 ilen=00000000
[   58.151582]         reason=00000000 qualification=0000000000000000
[   58.155286] IDTVectoring: info=00000000 errcode=00000000
[   58.157549] TSC Offset = 0xffffffd56d36b672
[   58.160120] TSC Multiplier = 0x0001000000000000
[   58.161827] TPR Threshold = 0x00
[   58.161831] virt-APIC addr = 0x0000000109668000
[   58.161835] EPT pointer = 0x000000010855205e
[   58.163304] Virtual processor ID = 0x0001
```

**Comment by liuw** [comment]
Can you also provide the model of the VM?

**Comment by sboeuf** [comment]
> Can you also provide the model of the VM?

Standard D64s_v5

**Comment by liuw** [comment]
A team member of mine bisected the tree and found the culprit. He plans to send a patch for KVM. It will take some time to trickle down to Ubuntu.

**Comment by rbradford** [comment]
We held back switch to jammy due to kernel issues but since those kernel issues made their way into focal. Hopefully we can now switch.

**Review by sboeuf — APPROVED** [review]

**Pull request merged**
