### PR TITLE
vmm:api: add add-user-device support in cloud-hypervisor.yaml

### PR DESCRIPTION
**Pull request by changruinj**
The change is missed when add "add-user-device" support in 53b2e19934abfe2920258e586e627498653b2371, use this commit to fix it.

Change-Id: Ifcfa4e94ce2342cc6c0723f65326f04b88bf2664

### CODE REVIEW

**Review by rbradford — CHANGES_REQUESTED** [review]
OpenAPI yaml validation is currently missing (see #5960) so we need to get a CI check for that before this can be integrated

**Comment by michael2012z** [comment]
> OpenAPI yaml validation is currently missing (see #5960) so we need to get a CI check for that before this can be integrated

Created https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5971 to enable OpenAPI validation.

**Comment by michael2012z** [comment]
@changruinj Please rebase the PR to the latest main branch, where the OpenAPI check is in place now.

**Review by michael2012z — APPROVED** [review]

**Review by rbradford — APPROVED** [review]

**Comment by rbradford** [comment]
Thank you!

**Pull request merged**
