### PR TITLE
Add CPU pinning support

### LINKED ISSUE #3298: CPU pinning
__Goal__

Pin a specific vCPU to a set of host CPUs. This is useful in the context of NUMA, making sure vCPUs and memory are consistently assigned for different NUMA nodes.

__Technical details__

From each vCPU thread, we're going to call `sched_setaffinity()` based on the value provided by the user, or simply don't invoke this syscall if nothing was specified.

__User interface__

- The most versatile option would be to give the user a way to describe the host cpuset for each vCPU. We could add `affinity=` option to the `cpus` parameter. An example would be `--cpus boot=2,affinity=0@0x3:1@0xc`, meaning vCPU 0 will be running on host CPU 0 or 1, while vCPU 1 will be running on host CPU 2 or 3.
- Another option would be to allow a host NUMA node to be specified for each vCPU. We could add `host_numa_node=` option to the `cpus` parameter. An example would be `--cpus boot=2,host_numa_node=0@1:1@0`, meaning vCPU 0 will be running on host CPUs from host NUMA node 1, while vCPU 1 will be running on host CPUs from host NUMA node 0.

Since CPU pinning is really a user superpower option, my opinion is that we shouldn't try to be too smart about it and simply give the user the tools to apply it. That's why the first option looks the most appropriate to me.

### PR DESCRIPTION
**Pull request by sboeuf**
This PR brings to Cloud Hypervisor the ability to pin each and every virtual CPU to a set of host CPUs.

Fixes #3298

### CODE REVIEW

**Comment by iggy** [comment]
Some documentation on use (outside of the integration tests) would be nice.

**Comment by sboeuf** [comment]
I opened #3317 to track the creation of a document for the `cpus` parameter (which I'll take care of right after that). This PR is ready to be reviewed/merged in the meantime.

**Review by likebreath — APPROVED** [review]
The changes look good to me. I am trying to understand what would be the good use case with the new `affinity` option?  

Looks like it is a "power-user" option, and can provide finer granularity of CPU pinning for vCPUs threads comparing to cgroups (that applies rules for the whole process). Is this the main benefit of using the `affinity` option (say over `cgroups`) from the upper VMM management layer?

**Review by rbradford — APPROVED** [review]

**Comment by sboeuf** [comment]
@likebreath yes the point is to give the user a finer granularity option without the need for an upper management layer to do it. It doesn't mean you can't have the upper layer do the work, but this way we provide a complete way for using NUMA from a CPU and memory perspective.

**Pull request merged**
