### PR TITLE
ci: AArch64: Enable basic virtio_vsock test case for AArch64

### PR DESCRIPTION
**Pull request by MrXinWang**
This commit enables the test case for testing the basic function of virtio_vsock (i.e. without the hotplug).

Signed-off-by: Henry Wang <Henry.Wang@arm.com>

### CODE REVIEW

**Comment by MrXinWang** [comment]
Hi @sboeuf @rbradford ! It is a little bit awkward to ask but can I ask a favor from either of you: Could you please follow [this guide](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/docs/custom-image.md) and update the AArch64 integration test image with [these packages](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/docs/custom-image.md#install-needed-packages) installed? These packages are used in the vsock test case and due to our company's policy, we can only upload/submit code to the community (either binary or image is forbidden)...Thanks!

**Comment by rbradford** [comment]
@MrXinWang Should be in the bucket: https://cloudhypervisorstorage.blob.core.windows.net/images/focal-server-cloudimg-arm64-custom.qcow2 and https://cloudhypervisorstorage.blob.core.windows.net/images/focal-server-cloudimg-arm64-custom.raw

**Comment by MrXinWang** [comment]
Hi @rbradford ! Thanks for uploading this! However a small bug happened while I tested this updated image:

I think when you tried to install the `socat` via apt, the DNS resolution failed and you changed the original `/etc/resolv.conf` to `/etc/resolv.conf.foo` and made a new `/etc/resolv.conf` which contains `nameserver 1.1.1.1`. The thing is...probably you forgot to change the original `resolv.conf` back from the `resolv.conf.foo` after installing packages. This will lead to the failure of this vsock test case, and the test case will stuck here https://github.com/cloud-hypervisor/cloud-hypervisor/blob/61c093f724ad92aa47576606abb94e2ecd8ecf4e/tests/integration.rs#L820 forever waiting...

Therefore, could you please just do the similar steps for customizing the image, and this time just run `mv resolv.conf.foo resolv.conf`? Great thanks!

**Comment by rbradford** [comment]
@MrXinWang Oops. Can you try again?

**Comment by MrXinWang** [comment]
Hi @rbradford ! The images work perfectly on my local machine and I've updated this PR :)

**Pull request merged**
